additive_expression ::= multiplicative_expression additive_expression[0] ;
additive_expression[0] ::= additive_expression[0] additive_expression[0][0] multiplicative_expression
  |  ;
additive_expression[0][0] ::= '+'
  | '-' ;
arguments ::= '(' arguments[0] ')' ;
arguments[0] ::= assignment_expression arguments[0][0]
  |  ;
arguments[0][0] ::= arguments[0][0] ',' assignment_expression
  |  ;
array_binding_pattern ::= '[' array_binding_pattern[0] array_binding_pattern[1] array_binding_pattern[2] array_binding_pattern[3] array_binding_pattern[4] ']' ;
array_binding_pattern[0] ::= array_binding_pattern[0][0] binding_element
  |  ;
array_binding_pattern[0][0] ::= ELISION
  |  ;
array_binding_pattern[1] ::= array_binding_pattern[1] ',' array_binding_pattern[1][0] binding_element
  |  ;
array_binding_pattern[1][0] ::= ELISION
  |  ;
array_binding_pattern[2] ::= array_binding_pattern[2][0] '...' binding_pattern
  |  ;
array_binding_pattern[2][0] ::= ','
  |  ;
array_binding_pattern[3] ::= ','
  |  ;
array_binding_pattern[4] ::= ELISION
  |  ;
array_literal ::= '[' array_literal[0] array_literal[1] array_literal[2] array_literal[3] ']' ;
array_literal[0] ::= array_literal[0][0] assignment_expression
  |  ;
array_literal[0][0] ::= ELISION
  |  ;
array_literal[1] ::= array_literal[1] ',' array_literal[1][0] assignment_expression
  |  ;
array_literal[1][0] ::= ELISION
  |  ;
array_literal[2] ::= ','
  |  ;
array_literal[3] ::= ELISION
  |  ;
arrow_function ::= arrow_parameters '=>' arrow_function[0] ;
arrow_function[0] ::= block
  | expression ;
arrow_parameters ::= IDENTIFIER
  | '(' arrow_parameters[0] ')' ;
arrow_parameters[0] ::= parameter_list
  |  ;
assignment_expression ::= yield_expression
  | arrow_function
  | conditional_expression
  | left_hand_side_expression assignment_expression[0] assignment_expression ;
assignment_expression[0] ::= '='
  | '+='
  | '-='
  | '*='
  | '/='
  | '%='
  | '<<='
  | '>>='
  | '>>>='
  | '&='
  | '^='
  | '|='
  | '**=' ;
binding_element ::= binding_pattern binding_element[0] ;
binding_element[0] ::= '=' expression
  |  ;
binding_pattern ::= IDENTIFIER
  | object_binding_pattern
  | array_binding_pattern ;
bitwise_and_expression ::= equality_expression bitwise_and_expression[0] ;
bitwise_and_expression[0] ::= bitwise_and_expression[0] '&' equality_expression
  |  ;
bitwise_or_expression ::= bitwise_xor_expression bitwise_or_expression[0] ;
bitwise_or_expression[0] ::= bitwise_or_expression[0] '|' bitwise_xor_expression
  |  ;
bitwise_xor_expression ::= bitwise_and_expression bitwise_xor_expression[0] ;
bitwise_xor_expression[0] ::= bitwise_xor_expression[0] '^' bitwise_and_expression
  |  ;
block ::= '{' block[0] '}' ;
block[0] ::= statement_list
  |  ;
break_statement ::= 'break' break_statement[0] break_statement[1] ;
break_statement[0] ::= IDENTIFIER
  |  ;
break_statement[1] ::= ';'
  |  ;
call_expression ::= member_expression arguments
  | 'super' arguments
  | call_expression arguments
  | call_expression '?.' arguments
  | call_expression '[' expression ']'
  | call_expression '?.' '[' expression ']'
  | call_expression '.' IDENTIFIER
  | call_expression '?.' IDENTIFIER
  | call_expression '.' private_identifier
  | call_expression '?.' private_identifier
  | call_expression template_literal ;
case_clause ::= 'case' expression ':' case_clause[0] ;
case_clause[0] ::= statement_list
  |  ;
case_clauses ::= case_clause case_clauses[0] ;
case_clauses[0] ::= case_clauses[0] case_clause
  |  ;
catch_clause ::= 'catch' catch_clause[0] block ;
catch_clause[0] ::= '(' binding_pattern ')'
  |  ;
class_body ::= '{' class_body[0] '}' ;
class_body[0] ::= class_body[0] class_member
  |  ;
class_declaration ::= 'class' class_declaration[0] class_declaration[1] class_body ;
class_declaration[0] ::= IDENTIFIER
  |  ;
class_declaration[1] ::= 'extends' expression
  |  ;
class_member ::= class_member[0] class_member[1]
  | ';' ;
class_member[0] ::= method_definition
  | field_definition ;
class_member[1] ::= ';'
  |  ;
class_property_name ::= property_name
  | private_identifier ;
coalesce_expression ::= logical_or_expression coalesce_expression[0] ;
coalesce_expression[0] ::= coalesce_expression[0] '??' logical_or_expression
  |  ;
conditional_expression ::= coalesce_expression conditional_expression[0] ;
conditional_expression[0] ::= '?' assignment_expression ':' assignment_expression
  |  ;
continue_statement ::= 'continue' continue_statement[0] continue_statement[1] ;
continue_statement[0] ::= IDENTIFIER
  |  ;
continue_statement[1] ::= ';'
  |  ;
debugger_statement ::= 'debugger' debugger_statement[0] ;
debugger_statement[0] ::= ';'
  |  ;
declaration_statement ::= declaration_statement[0] variable_declaration_list declaration_statement[1] ;
declaration_statement[0] ::= 'var'
  | 'let'
  | 'const' ;
declaration_statement[1] ::= ';'
  |  ;
default_clause ::= 'default' ':' default_clause[0] ;
default_clause[0] ::= statement_list
  |  ;
default_import ::= IDENTIFIER ;
equality_expression ::= relational_expression equality_expression[0] ;
equality_expression[0] ::= equality_expression[0] equality_expression[0][0] relational_expression
  |  ;
equality_expression[0][0] ::= '=='
  | '!='
  | '==='
  | '!==' ;
exponentiation_expression ::= unary_expression exponentiation_expression[0] ;
exponentiation_expression[0] ::= '**' exponentiation_expression
  |  ;
export_specifier ::= IDENTIFIER export_specifier[0] ;
export_specifier[0] ::= 'as' IDENTIFIER
  |  ;
export_statement ::= 'export' export_statement[0] export_statement[1] ;
export_statement[0] ::= 'default' export_statement[0][0]
  | '*' export_statement[0][1]
  | named_exports export_statement[0][2]
  | declaration_statement
  | class_declaration ;
export_statement[0][0] ::= function_declaration
  | class_declaration
  | expression ;
export_statement[0][1] ::= 'from' STRING_LITERAL
  |  ;
export_statement[0][2] ::= 'from' STRING_LITERAL
  |  ;
export_statement[1] ::= ';'
  |  ;
expression ::= assignment_expression ;
expression_statement ::= expression expression_statement[0] ;
expression_statement[0] ::= ';'
  |  ;
field_definition ::= field_definition[0] class_property_name field_definition[1] ;
field_definition[0] ::= 'static'
  |  ;
field_definition[1] ::= '=' expression
  |  ;
finally_clause ::= 'finally' block ;
formal_parameter ::= binding_pattern formal_parameter[0] ;
formal_parameter[0] ::= '=' expression
  |  ;
function_declaration ::= function_declaration[0] 'function' function_declaration[1] function_declaration[2] '(' function_declaration[3] ')' block ;
function_declaration[0] ::= 'async'
  |  ;
function_declaration[1] ::= '*'
  |  ;
function_declaration[2] ::= IDENTIFIER
  |  ;
function_declaration[3] ::= parameter_list
  |  ;
function_expression ::= function_expression[0] 'function' function_expression[1] function_expression[2] '(' function_expression[3] ')' block ;
function_expression[0] ::= 'async'
  |  ;
function_expression[1] ::= '*'
  |  ;
function_expression[2] ::= IDENTIFIER
  |  ;
function_expression[3] ::= parameter_list
  |  ;
if_statement ::= 'if' '(' expression ')' statement if_statement[0] ;
if_statement[0] ::= 'else' statement
  |  ;
import_clause ::= default_import
  | named_imports
  | namespace_import
  | default_import ',' import_clause[0] ;
import_clause[0] ::= named_imports
  | namespace_import ;
import_specifier ::= IDENTIFIER import_specifier[0] ;
import_specifier[0] ::= 'as' IDENTIFIER
  |  ;
import_statement ::= 'import' import_statement[0] import_statement[1] ;
import_statement[0] ::= import_clause 'from' STRING_LITERAL
  | STRING_LITERAL ;
import_statement[1] ::= ';'
  |  ;
iteration_statement ::= 'while' '(' expression ')' statement
  | 'do' statement 'while' '(' expression ')' ';'
  | 'for' '(' iteration_statement[0] ';' iteration_statement[1] ';' iteration_statement[2] ')' statement
  | 'for' '(' iteration_statement[3] binding_pattern iteration_statement[4] expression ')' statement
  | 'for' '(' iteration_statement[5] ';' iteration_statement[6] ';' iteration_statement[7] ')' statement ;
iteration_statement[0] ::= iteration_statement[0][0] variable_declaration_list
  |  ;
iteration_statement[0][0] ::= 'var'
  | 'let'
  | 'const' ;
iteration_statement[1] ::= expression
  |  ;
iteration_statement[2] ::= expression
  |  ;
iteration_statement[3] ::= iteration_statement[3][0]
  |  ;
iteration_statement[3][0] ::= 'var'
  | 'let'
  | 'const' ;
iteration_statement[4] ::= 'in'
  | 'of' ;
iteration_statement[5] ::= expression
  |  ;
iteration_statement[6] ::= expression
  |  ;
iteration_statement[7] ::= expression
  |  ;
labeled_statement ::= IDENTIFIER ':' statement ;
left_hand_side_expression ::= new_expression
  | call_expression ;
literal ::= NULL_LITERAL
  | BOOLEAN_LITERAL
  | NUMERIC_LITERAL
  | BIGINT_LITERAL
  | STRING_LITERAL
  | REGULAR_EXPRESSION_LITERAL
  | template_literal ;
logical_and_expression ::= bitwise_or_expression logical_and_expression[0] ;
logical_and_expression[0] ::= logical_and_expression[0] '&&' bitwise_or_expression
  |  ;
logical_or_expression ::= logical_and_expression logical_or_expression[0] ;
logical_or_expression[0] ::= logical_or_expression[0] '||' logical_and_expression
  |  ;
member_expression ::= primary_expression
  | member_expression '[' expression ']'
  | member_expression '?.' '[' expression ']'
  | member_expression '.' IDENTIFIER
  | member_expression '?.' IDENTIFIER
  | member_expression '.' private_identifier
  | member_expression '?.' private_identifier
  | 'new' member_expression arguments
  | member_expression template_literal ;
method_definition ::= method_definition[0] method_definition[1] method_definition[2] class_property_name '(' method_definition[3] ')' block ;
method_definition[0] ::= 'static'
  |  ;
method_definition[1] ::= method_definition[1][0]
  |  ;
method_definition[1][0] ::= 'get'
  | 'set' ;
method_definition[2] ::= method_definition[2][0]
  |  ;
method_definition[2][0] ::= 'async'
  | '*' ;
method_definition[3] ::= parameter_list
  |  ;
multiplicative_expression ::= exponentiation_expression multiplicative_expression[0] ;
multiplicative_expression[0] ::= multiplicative_expression[0] multiplicative_expression[0][0] exponentiation_expression
  |  ;
multiplicative_expression[0][0] ::= '*'
  | '/'
  | '%' ;
named_exports ::= '{' named_exports[0] named_exports[1] '}' ;
named_exports[0] ::= export_specifier named_exports[0][0]
  |  ;
named_exports[0][0] ::= named_exports[0][0] ',' export_specifier
  |  ;
named_exports[1] ::= ','
  |  ;
named_imports ::= '{' named_imports[0] named_imports[1] '}' ;
named_imports[0] ::= import_specifier named_imports[0][0]
  |  ;
named_imports[0][0] ::= named_imports[0][0] ',' import_specifier
  |  ;
named_imports[1] ::= ','
  |  ;
namespace_import ::= '*' 'as' IDENTIFIER ;
new_expression ::= member_expression
  | 'new' new_expression ;
object_binding_pattern ::= '{' object_binding_pattern[0] object_binding_pattern[1] object_binding_pattern[2] '}' ;
object_binding_pattern[0] ::= property_binding object_binding_pattern[0][0]
  |  ;
object_binding_pattern[0][0] ::= object_binding_pattern[0][0] ',' property_binding
  |  ;
object_binding_pattern[1] ::= object_binding_pattern[1][0] '...' IDENTIFIER
  |  ;
object_binding_pattern[1][0] ::= ','
  |  ;
object_binding_pattern[2] ::= ','
  |  ;
object_literal ::= '{' object_literal[0] object_literal[1] '}' ;
object_literal[0] ::= property_assignment object_literal[0][0]
  |  ;
object_literal[0][0] ::= object_literal[0][0] ',' property_assignment
  |  ;
object_literal[1] ::= ','
  |  ;
parameter_list ::= formal_parameter parameter_list[0] parameter_list[1] ;
parameter_list[0] ::= parameter_list[0] ',' formal_parameter
  |  ;
parameter_list[1] ::= parameter_list[1][0] '...' binding_pattern
  |  ;
parameter_list[1][0] ::= ','
  |  ;
postfix_expression ::= left_hand_side_expression postfix_expression[0] ;
postfix_expression[0] ::= postfix_expression[0][0]
  |  ;
postfix_expression[0][0] ::= '++'
  | '--' ;
primary_expression ::= 'this'
  | 'super'
  | IDENTIFIER
  | literal
  | array_literal
  | object_literal
  | function_expression
  | '(' expression ')' ;
private_identifier ::= '#' IDENTIFIER ;
program ::= program[0] EOF ;
program[0] ::= statement_list
  |  ;
property_assignment ::= property_assignment[0] property_assignment[1] property_name '(' property_assignment[2] ')' block
  | 'get' property_name '(' ')' block
  | 'set' property_name '(' IDENTIFIER ')' block
  | property_name ':' assignment_expression
  | '...' assignment_expression
  | IDENTIFIER ;
property_assignment[0] ::= 'async'
  |  ;
property_assignment[1] ::= '*'
  |  ;
property_assignment[2] ::= parameter_list
  |  ;
property_binding ::= IDENTIFIER property_binding[0]
  | property_name ':' binding_pattern property_binding[1] ;
property_binding[0] ::= '=' expression
  |  ;
property_binding[1] ::= '=' expression
  |  ;
property_name ::= IDENTIFIER
  | STRING_LITERAL
  | NUMERIC_LITERAL
  | '[' expression ']' ;
relational_expression ::= shift_expression relational_expression[0] ;
relational_expression[0] ::= relational_expression[0] relational_expression[0][0] shift_expression
  |  ;
relational_expression[0][0] ::= '<'
  | '>'
  | '<='
  | '>='
  | 'instanceof'
  | 'in' ;
return_statement ::= 'return' return_statement[0] return_statement[1] ;
return_statement[0] ::= expression
  |  ;
return_statement[1] ::= ';'
  |  ;
shift_expression ::= additive_expression shift_expression[0] ;
shift_expression[0] ::= shift_expression[0] shift_expression[0][0] additive_expression
  |  ;
shift_expression[0][0] ::= '<<'
  | '>>'
  | '>>>' ;
start' ::= program ;
statement ::= block
  | declaration_statement
  | if_statement
  | iteration_statement
  | switch_statement
  | with_statement
  | try_statement
  | function_declaration
  | return_statement
  | break_statement
  | continue_statement
  | throw_statement
  | debugger_statement
  | labeled_statement
  | class_declaration
  | import_statement
  | export_statement
  | expression_statement ;
statement_list ::= statement statement_list[0] ;
statement_list[0] ::= statement_list[0] statement
  |  ;
switch_statement ::= 'switch' '(' expression ')' '{' switch_statement[0] switch_statement[1] '}' ;
switch_statement[0] ::= case_clauses
  |  ;
switch_statement[1] ::= default_clause switch_statement[1][0]
  |  ;
switch_statement[1][0] ::= case_clauses
  |  ;
template_literal ::= '`' TEMPLATE_CHARS '`' ;
throw_statement ::= 'throw' expression throw_statement[0] ;
throw_statement[0] ::= ';'
  |  ;
try_statement ::= 'try' block try_statement[0] ;
try_statement[0] ::= catch_clause try_statement[0][0]
  | finally_clause ;
try_statement[0][0] ::= finally_clause
  |  ;
unary_expression ::= postfix_expression
  | unary_expression[0] unary_expression ;
unary_expression[0] ::= 'delete'
  | 'void'
  | 'typeof'
  | '++'
  | '--'
  | '+'
  | '-'
  | '~'
  | '!'
  | 'await' ;
variable_declaration ::= binding_pattern variable_declaration[0] ;
variable_declaration[0] ::= '=' expression
  |  ;
variable_declaration_list ::= variable_declaration variable_declaration_list[0] ;
variable_declaration_list[0] ::= variable_declaration_list[0] ',' variable_declaration
  |  ;
with_statement ::= 'with' '(' expression ')' statement ;
yield_expression ::= 'yield' yield_expression[0] yield_expression[1] ;
yield_expression[0] ::= '*'
  |  ;
yield_expression[1] ::= expression
  |  ;
