additive_expression ::= multiplicative_expression additive_expression[0] ;
additive_expression[0] ::= additive_expression[0] additive_expression[0][0] multiplicative_expression
  |  ;
additive_expression[0][0] ::= '+'
  | '-' ;
arguments ::= '(' arguments[0] ')' ;
arguments[0] ::= spread_element arguments[0][0]
  |  ;
arguments[0][0] ::= arguments[0][0] ',' spread_element
  |  ;
array_binding_pattern ::= '[' array_binding_pattern[0] array_binding_pattern[1] ']' ;
array_binding_pattern[0] ::= binding_pattern array_binding_pattern[0][0]
  |  ;
array_binding_pattern[0][0] ::= array_binding_pattern[0][0] ',' binding_pattern
  |  ;
array_binding_pattern[1] ::= ','
  |  ;
array_literal ::= '[' array_literal[0] array_literal[1] ']' ;
array_literal[0] ::= spread_element array_literal[0][0]
  |  ;
array_literal[0][0] ::= array_literal[0][0] ',' spread_element
  |  ;
array_literal[1] ::= ','
  |  ;
arrow_function ::= arrow_parameters '=>' arrow_function[0] ;
arrow_function[0] ::= block
  | expression ;
arrow_parameters ::= IDENTIFIER
  | '(' arrow_parameters[0] ')' ;
arrow_parameters[0] ::= parameter_list
  |  ;
assignment_expression ::= arrow_function
  | conditional_expression
  | left_hand_side_expression assignment_expression[0] assignment_expression ;
assignment_expression[0] ::= '='
  | '+='
  | '-='
  | '*='
  | '/='
  | '%='
  | '**=' ;
binding_pattern ::= IDENTIFIER
  | object_binding_pattern
  | array_binding_pattern ;
block ::= '{' block[0] '}' ;
block[0] ::= statement_list
  |  ;
break_statement ::= 'break' break_statement[0] ;
break_statement[0] ::= ';'
  |  ;
call_expression ::= member_expression arguments
  | call_expression arguments
  | call_expression '[' expression ']'
  | call_expression '.' IDENTIFIER ;
case_clause ::= 'case' expression ':' case_clause[0] ;
case_clause[0] ::= statement_list
  |  ;
catch_clause ::= 'catch' catch_clause[0] block ;
catch_clause[0] ::= '(' binding_pattern ')'
  |  ;
class_body ::= '{' class_body[0] '}' ;
class_body[0] ::= class_body[0] class_member
  |  ;
class_declaration ::= 'class' IDENTIFIER class_declaration[0] class_body ;
class_declaration[0] ::= 'extends' expression
  |  ;
class_member ::= method_definition class_member[0] ;
class_member[0] ::= ';'
  |  ;
conditional_expression ::= logical_or_expression conditional_expression[0] ;
conditional_expression[0] ::= '?' expression ':' expression
  |  ;
continue_statement ::= 'continue' continue_statement[0] ;
continue_statement[0] ::= ';'
  |  ;
declaration_statement ::= declaration_statement[0] variable_declaration_list declaration_statement[1] ;
declaration_statement[0] ::= 'var'
  | 'let'
  | 'const' ;
declaration_statement[1] ::= ';'
  |  ;
default_clause ::= 'default' ':' default_clause[0] ;
default_clause[0] ::= statement_list
  |  ;
equality_expression ::= relational_expression equality_expression[0] ;
equality_expression[0] ::= equality_expression[0] equality_expression[0][0] relational_expression
  |  ;
equality_expression[0][0] ::= '=='
  | '!='
  | '==='
  | '!==' ;
exponentiation_expression ::= unary_expression exponentiation_expression[0] ;
exponentiation_expression[0] ::= '**' exponentiation_expression
  |  ;
expression ::= assignment_expression ;
expression_statement ::= expression expression_statement[0] ;
expression_statement[0] ::= ';'
  |  ;
finally_clause ::= 'finally' block ;
formal_parameter ::= binding_pattern formal_parameter[0] ;
formal_parameter[0] ::= '=' expression
  |  ;
function_declaration ::= 'function' IDENTIFIER '(' function_declaration[0] ')' block ;
function_declaration[0] ::= parameter_list
  |  ;
function_expression ::= 'function' function_expression[0] '(' function_expression[1] ')' block ;
function_expression[0] ::= IDENTIFIER
  |  ;
function_expression[1] ::= parameter_list
  |  ;
if_statement ::= 'if' '(' expression ')' statement if_statement[0] ;
if_statement[0] ::= 'else' statement
  |  ;
iteration_statement ::= 'while' '(' expression ')' statement
  | 'do' statement 'while' '(' expression ')' ';'
  | 'for' '(' iteration_statement[0] ';' iteration_statement[1] ';' iteration_statement[2] ')' statement
  | 'for' '(' iteration_statement[3] binding_pattern iteration_statement[4] expression ')' statement ;
iteration_statement[0] ::= iteration_statement[0][0] variable_declaration_list
  |  ;
iteration_statement[0][0] ::= 'var'
  | 'let'
  | 'const' ;
iteration_statement[1] ::= expression
  |  ;
iteration_statement[2] ::= expression
  |  ;
iteration_statement[3] ::= iteration_statement[3][0]
  |  ;
iteration_statement[3][0] ::= 'var'
  | 'let'
  | 'const' ;
iteration_statement[4] ::= 'in'
  | 'of' ;
left_hand_side_expression ::= member_expression
  | call_expression ;
literal ::= 'null'
  | 'true'
  | 'false'
  | NUMERIC_LITERAL
  | STRING_LITERAL
  | template_literal ;
logical_and_expression ::= equality_expression logical_and_expression[0] ;
logical_and_expression[0] ::= logical_and_expression[0] '&&' equality_expression
  |  ;
logical_or_expression ::= logical_and_expression logical_or_expression[0] ;
logical_or_expression[0] ::= logical_or_expression[0] '||' logical_and_expression
  |  ;
member_expression ::= primary_expression
  | member_expression '[' expression ']'
  | member_expression '.' IDENTIFIER
  | 'new' member_expression member_expression[0] ;
member_expression[0] ::= arguments
  |  ;
method_definition ::= IDENTIFIER '(' method_definition[0] ')' block ;
method_definition[0] ::= parameter_list
  |  ;
multiplicative_expression ::= exponentiation_expression multiplicative_expression[0] ;
multiplicative_expression[0] ::= multiplicative_expression[0] multiplicative_expression[0][0] exponentiation_expression
  |  ;
multiplicative_expression[0][0] ::= '*'
  | '/'
  | '%' ;
object_binding_pattern ::= '{' object_binding_pattern[0] object_binding_pattern[1] '}' ;
object_binding_pattern[0] ::= property_binding object_binding_pattern[0][0]
  |  ;
object_binding_pattern[0][0] ::= object_binding_pattern[0][0] ',' property_binding
  |  ;
object_binding_pattern[1] ::= ','
  |  ;
object_literal ::= '{' object_literal[0] object_literal[1] '}' ;
object_literal[0] ::= property_assignment object_literal[0][0]
  |  ;
object_literal[0][0] ::= object_literal[0][0] ',' property_assignment
  |  ;
object_literal[1] ::= ','
  |  ;
parameter_list ::= formal_parameter parameter_list[0] ;
parameter_list[0] ::= parameter_list[0] ',' formal_parameter
  |  ;
postfix_expression ::= left_hand_side_expression postfix_expression[0] ;
postfix_expression[0] ::= postfix_expression[0][0]
  |  ;
postfix_expression[0][0] ::= '++'
  | '--' ;
primary_expression ::= 'this'
  | 'super'
  | IDENTIFIER
  | literal
  | array_literal
  | object_literal
  | function_expression
  | '(' expression ')' ;
program ::= program[0] EOF ;
program[0] ::= statement_list
  |  ;
property_assignment ::= property_name ':' expression
  | IDENTIFIER
  | '...' expression
  | IDENTIFIER '(' property_assignment[0] ')' block ;
property_assignment[0] ::= parameter_list
  |  ;
property_binding ::= IDENTIFIER
  | IDENTIFIER ':' binding_pattern ;
property_name ::= IDENTIFIER
  | STRING_LITERAL
  | NUMERIC_LITERAL
  | '[' expression ']' ;
relational_expression ::= additive_expression relational_expression[0] ;
relational_expression[0] ::= relational_expression[0] relational_expression[0][0] additive_expression
  |  ;
relational_expression[0][0] ::= '<'
  | '>'
  | '<='
  | '>='
  | 'instanceof'
  | 'in' ;
return_statement ::= 'return' return_statement[0] return_statement[1] ;
return_statement[0] ::= expression
  |  ;
return_statement[1] ::= ';'
  |  ;
spread_element ::= spread_element[0] expression ;
spread_element[0] ::= '...'
  |  ;
start' ::= program ;
statement ::= block
  | declaration_statement
  | if_statement
  | iteration_statement
  | switch_statement
  | try_statement
  | function_declaration
  | class_declaration
  | return_statement
  | break_statement
  | continue_statement
  | expression_statement ;
statement_list ::= statement statement_list[0] ;
statement_list[0] ::= statement_list[0] statement
  |  ;
switch_statement ::= 'switch' '(' expression ')' '{' switch_statement[0] switch_statement[1] '}' ;
switch_statement[0] ::= switch_statement[0] case_clause
  |  ;
switch_statement[1] ::= default_clause switch_statement[1][0]
  |  ;
switch_statement[1][0] ::= switch_statement[1][0] case_clause
  |  ;
template_literal ::= '`' template_literal[0] '`' ;
template_literal[0] ::= template_literal[0] template_literal[0][0]
  |  ;
template_literal[0][0] ::= TEMPLATE_CHARS
  | template_substitution ;
template_substitution ::= '${' expression '}' ;
try_statement ::= 'try' block try_statement[0] ;
try_statement[0] ::= catch_clause try_statement[0][0]
  | finally_clause ;
try_statement[0][0] ::= finally_clause
  |  ;
unary_expression ::= postfix_expression
  | unary_expression[0] unary_expression ;
unary_expression[0] ::= 'delete'
  | 'typeof'
  | 'void'
  | '++'
  | '--'
  | '+'
  | '-'
  | '~'
  | '!' ;
variable_declaration ::= binding_pattern variable_declaration[0] ;
variable_declaration[0] ::= '=' expression
  |  ;
variable_declaration_list ::= variable_declaration variable_declaration_list[0] ;
variable_declaration_list[0] ::= variable_declaration_list[0] ',' variable_declaration
  |  ;
