root ::= ( _OS_KEY ( _def12 | _def24 | _def28 | _json_object | _def10 | _def18 | _def6 | _def5 | _def25 | _def1 | ( _json_object ) | _def21 | _def11 | _def13 | _def14 | _def7 | _def17 | _def19 | _def27 | _def9 | JSON_BOOL | _def8 | _def22 | _def23 | _def4 | _def2 | _def26 | _def20 | _def16 | _def15 | _def3 ) ( _OC_KEY ( _def12 | _def24 | _def28 | _json_object | _def10 | _def18 | _def6 | _def5 | _def25 | _def1 | ( _json_object ) | _def21 | _def11 | _def13 | _def14 | _def7 | _def17 | _def19 | _def27 | _def9 | JSON_BOOL | _def8 | _def22 | _def23 | _def4 | _def2 | _def26 | _def20 | _def16 | _def15 | _def3 ) )* '}' ) | '{}' ;
WS ::=  ;
JSON_STRING ::= '"' STRING_CHARS '"' ;
STRING_CHARS ::= ( ( STRING_CHAR | ESCAPE_SEQ ) )* ;
STRING_CHAR ::= [^"\\\x00-\x1f] ;
ESCAPE_SEQ ::= '\\' ( ["\\/bfnrt] | 'u' HEX HEX HEX HEX ) ;
HEX ::= [0-9a-fA-F] ;
JSON_INTEGER ::= ( '-' )? ( '0' | [1-9] ( [0-9] )* ) ;
JSON_NUMBER ::= JSON_INTEGER ( '.' DIGITS )? ( EXPONENT )? ;
DIGITS ::= [0-9] ( [0-9] )* ;
EXPONENT ::= [eE] ( [+-] )? DIGITS ;
JSON_BOOL ::= ( 'true' | 'false' ) ;
JSON_NULL ::= 'null' ;
_json_value ::= ( _json_object | _json_array | JSON_STRING | JSON_NUMBER | JSON_BOOL | JSON_NULL ) ;
_json_object ::= '{' ( _json_kv ( ',' _json_kv )* )? '}' ;
_json_kv ::= JSON_STRING ':' _json_value ;
_json_array ::= '[' ( _json_value ( ',' _json_value )* )? ']' ;
KEY_CHAR ::= [a-z0-9_.] ;
JSON_KEY ::= KEY_CHAR+ ;
_OS_KEY ::= '{"' JSON_KEY '":' ;
_OC_KEY ::= ',"' JSON_KEY '":' ;
_alt140 ::= ( _OS_KEY _pv141 ( _OC_KEY _pv141 )* '}' ) | '{}' ;
_alt150 ::= ( _OS_KEY ( JSON_BOOL | _pv48 ) ( _OC_KEY ( JSON_BOOL | _pv48 ) )* '}' ) | '{}' ;
_alt153 ::= ( _OS_KEY ( JSON_BOOL | _pv48 ) ( _OC_KEY ( JSON_BOOL | _pv48 ) )* '}' ) | '{}' ;
_alt208 ::= ( _OS_KEY _def209 ( _OC_KEY _def209 )* '}' ) | '{}' ;
_alt226 ::= ( _OS_KEY ( _def227 | _def228 | _def229 ) ( _OC_KEY ( _def227 | _def228 | _def229 ) )* '}' ) | '{}' ;
_alt231 ::= ( _OS_KEY _def232 ( _OC_KEY _def232 )* '}' ) | '{}' ;
_alt234 ::= ( _OS_KEY _def235 ( _OC_KEY _def235 )* '}' ) | '{}' ;
_alt254 ::= ( _OS_KEY _pv48 ( _OC_KEY _pv48 )* '}' ) | '{}' ;
_alt257 ::= ( _OS_KEY _pv48 ( _OC_KEY _pv48 )* '}' ) | '{}' ;
_alt260 ::= ( _OS_KEY _pv48 ( _OC_KEY _pv48 )* '}' ) | '{}' ;
_alt263 ::= ( _OS_KEY _pv48 ( _OC_KEY _pv48 )* '}' ) | '{}' ;
_alt315 ::= ( _OS_KEY ( '"header"' | JSON_STRING ) ( _OC_KEY ( '"header"' | JSON_STRING ) )* '}' ) | '{}' ;
_alt317 ::= ( _OS_KEY ( JSON_STRING | '"cookie"' ) ( _OC_KEY ( JSON_STRING | '"cookie"' ) )* '}' ) | '{}' ;
_alt319 ::= ( _OS_KEY _def320 ( _OC_KEY _def320 )* '}' ) | '{}' ;
_alt322 ::= ( _OS_KEY _def323 ( _OC_KEY _def323 )* '}' ) | '{}' ;
_alt325 ::= ( _OS_KEY _pv48 ( _OC_KEY _pv48 )* '}' ) | '{}' ;
_alt328 ::= ( _OS_KEY _pv329 ( _OC_KEY _pv329 )* '}' ) | '{}' ;
_alt333 ::= ( _OS_KEY _pv329 ( _OC_KEY _pv329 )* '}' ) | '{}' ;
_alt336 ::= ( _OS_KEY _pv329 ( _OC_KEY _pv329 )* '}' ) | '{}' ;
_alt339 ::= ( _OS_KEY _def331 ( _OC_KEY _def331 )* '}' ) | '{}' ;
_alt341 ::= ( _OS_KEY _pv342 ( _OC_KEY _pv342 )* '}' ) | '{}' ;
_alt344 ::= ( _OS_KEY _pv342 ( _OC_KEY _pv342 )* '}' ) | '{}' ;
_alt347 ::= ( _OS_KEY _def216 ( _OC_KEY _def216 )* '}' ) | '{}' ;
_alt352 ::= ( _OS_KEY _pv353 ( _OC_KEY _pv353 )* '}' ) | '{}' ;
_alt356 ::= ( _OS_KEY _pv353 ( _OC_KEY _pv353 )* '}' ) | '{}' ;
_alt359 ::= ( _OS_KEY _pv353 ( _OC_KEY _pv353 )* '}' ) | '{}' ;
_alt362 ::= ( _OS_KEY _def354 ( _OC_KEY _def354 )* '}' ) | '{}' ;
_alt364 ::= ( _OS_KEY _pv365 ( _OC_KEY _pv365 )* '}' ) | '{}' ;
_alt367 ::= ( _OS_KEY _pv365 ( _OC_KEY _pv365 )* '}' ) | '{}' ;
_alt370 ::= ( _OS_KEY _def222 ( _OC_KEY _def222 )* '}' ) | '{}' ;
_alt375 ::= ( _OS_KEY JSON_STRING ( _OC_KEY JSON_STRING )* '}' ) | '{}' ;
_alt377 ::= ( _OS_KEY JSON_STRING ( _OC_KEY JSON_STRING )* '}' ) | '{}' ;
_alt379 ::= ( _OS_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt381 ::= ( _OS_KEY JSON_STRING ( _OC_KEY JSON_STRING )* '}' ) | '{}' ;
_alt459 ::= '[' ( JSON_BOOL ( ',' JSON_BOOL )* )? ']' ;
_alt460 ::= '[' ( JSON_INTEGER ( ',' JSON_INTEGER )* )? ']' ;
_alt463 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt465 ::= ( _OS_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt467 ::= ( _OS_KEY ( '"reason"' ) ( _OC_KEY ( '"reason"' ) )* '}' ) | '{}' ;
_alt469 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_alt471 ::= ( _OS_KEY ( ( '"string"' | '"hash"' ) | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( '"string"' | '"hash"' ) | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt473 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt475 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt477 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_alt479 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_alt481 ::= ( _OS_KEY JSON_STRING ( _OC_KEY JSON_STRING )* '}' ) | '{}' ;
_alt483 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt485 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt487 ::= ( _OS_KEY ( '"code"' | '"reason"' ) ( _OC_KEY ( '"code"' | '"reason"' ) )* '}' ) | '{}' ;
_alt489 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_alt491 ::= ( _OS_KEY ( '"count"' | '"bool"' ) ( _OC_KEY ( '"count"' | '"bool"' ) )* '}' ) | '{}' ;
_alt493 ::= ( _OS_KEY ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) ( _OC_KEY ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) )* '}' ) | '{}' ;
_alt495 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_alt497 ::= ( _OS_KEY ( '"hexadecimal"' | '"open_telemetry"' | '"decimal"' | '"datadog"' | '"uuid"' ) ( _OC_KEY ( '"hexadecimal"' | '"open_telemetry"' | '"decimal"' | '"datadog"' | '"uuid"' ) )* '}' ) | '{}' ;
_alt499 ::= ( _OS_KEY _pv500 ( _OC_KEY _pv500 )* '}' ) | '{}' ;
_alt503 ::= ( _OS_KEY _pv500 ( _OC_KEY _pv500 )* '}' ) | '{}' ;
_alt506 ::= ( _OS_KEY _pv500 ( _OC_KEY _pv500 )* '}' ) | '{}' ;
_alt509 ::= ( _OS_KEY _def501 ( _OC_KEY _def501 )* '}' ) | '{}' ;
_alt511 ::= ( _OS_KEY _pv512 ( _OC_KEY _pv512 )* '}' ) | '{}' ;
_alt514 ::= ( _OS_KEY _pv512 ( _OC_KEY _pv512 )* '}' ) | '{}' ;
_alt517 ::= ( _OS_KEY _def349 ( _OC_KEY _def349 )* '}' ) | '{}' ;
_alt519 ::= ( _OS_KEY ( ( '"string"' | '"hash"' ) | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( '"string"' | '"hash"' ) | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt521 ::= ( _OS_KEY ( '"string"' ) ( _OC_KEY ( '"string"' ) )* '}' ) | '{}' ;
_alt523 ::= ( _OS_KEY ( ( '"string"' | '"aliases"' | '"depth"' | '"height"' | '"root_fields"' ) | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( '"string"' | '"aliases"' | '"depth"' | '"height"' | '"root_fields"' ) | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt525 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt527 ::= ( _OS_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt529 ::= ( _OS_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt531 ::= ( _OS_KEY ( '"code"' | '"reason"' ) ( _OC_KEY ( '"code"' | '"reason"' ) )* '}' ) | '{}' ;
_alt533 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt535 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt537 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt539 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt541 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt543 ::= ( _OS_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt545 ::= ( _OS_KEY ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) ( _OC_KEY ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) )* '}' ) | '{}' ;
_alt547 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_alt549 ::= ( _OS_KEY ( '"reason"' ) ( _OC_KEY ( '"reason"' ) )* '}' ) | '{}' ;
_alt551 ::= ( _OS_KEY ( '"estimated"' | '"actual"' | '"delta"' | '"result"' ) ( _OC_KEY ( '"estimated"' | '"actual"' | '"delta"' | '"result"' ) )* '}' ) | '{}' ;
_alt553 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_alt558 ::= ( _OS_KEY _pv559 ( _OC_KEY _pv559 )* '}' ) | '{}' ;
_alt563 ::= ( _OS_KEY _pv564 ( _OC_KEY _pv564 )* '}' ) | '{}' ;
_alt575 ::= ( _OS_KEY ( _def576 | ( '"info"' | '"warn"' | '"error"' | '"off"' ) ) ( _OC_KEY ( _def576 | ( '"info"' | '"warn"' | '"error"' | '"off"' ) ) )* '}' ) | '{}' ;
_alt580 ::= ( _OS_KEY ( _def216 | ( '"info"' | '"warn"' | '"error"' | '"off"' ) ) ( _OC_KEY ( _def216 | ( '"info"' | '"warn"' | '"error"' | '"off"' ) ) )* '}' ) | '{}' ;
_alt584 ::= ( _OS_KEY ( _def349 | ( '"info"' | '"warn"' | '"error"' | '"off"' ) ) ( _OC_KEY ( _def349 | ( '"info"' | '"warn"' | '"error"' | '"off"' ) ) )* '}' ) | '{}' ;
_alt588 ::= ( _OS_KEY ( _def222 | ( '"info"' | '"warn"' | '"error"' | '"off"' ) ) ( _OC_KEY ( _def222 | ( '"info"' | '"warn"' | '"error"' | '"off"' ) ) )* '}' ) | '{}' ;
_alt592 ::= ( _OS_KEY _def593 ( _OC_KEY _def593 )* '}' ) | '{}' ;
_alt596 ::= ( _OS_KEY _def578 ( _OC_KEY _def578 )* '}' ) | '{}' ;
_alt600 ::= ( _OS_KEY _def601 ( _OC_KEY _def601 )* '}' ) | '{}' ;
_alt606 ::= ( _OS_KEY _json_object ( _OC_KEY _json_object )* '}' ) | '{}' ;
_alt608 ::= ( _OS_KEY _def609 ( _OC_KEY _def609 )* '}' ) | '{}' ;
_alt611 ::= ( _OS_KEY _def582 ( _OC_KEY _def582 )* '}' ) | '{}' ;
_alt614 ::= ( _OS_KEY _def586 ( _OC_KEY _def586 )* '}' ) | '{}' ;
_alt617 ::= ( _OS_KEY _def590 ( _OC_KEY _def590 )* '}' ) | '{}' ;
_alt631 ::= ( _OS_KEY ( ( '"string"' | '"hash"' ) | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( '"string"' | '"hash"' ) | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt633 ::= ( _OS_KEY ( '"string"' ) ( _OC_KEY ( '"string"' ) )* '}' ) | '{}' ;
_alt635 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_alt637 ::= ( _OS_KEY ( ( '"string"' ) | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( '"string"' ) | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt639 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt641 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt643 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt645 ::= ( _OS_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt647 ::= ( _OS_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt649 ::= ( _OS_KEY ( '"code"' | '"reason"' ) ( _OC_KEY ( '"code"' | '"reason"' ) )* '}' ) | '{}' ;
_alt651 ::= ( _OS_KEY ( JSON_BOOL | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_BOOL | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt653 ::= ( _OS_KEY ( ( '"string"' | '"hash"' ) | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( '"string"' | '"hash"' ) | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt655 ::= ( _OS_KEY ( '"string"' ) ( _OC_KEY ( '"string"' ) )* '}' ) | '{}' ;
_alt657 ::= ( _OS_KEY ( ( '"string"' | '"aliases"' | '"depth"' | '"height"' | '"root_fields"' ) | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( '"string"' | '"aliases"' | '"depth"' | '"height"' | '"root_fields"' ) | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt659 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt661 ::= ( _OS_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt663 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt665 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt667 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_alt669 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt671 ::= ( _OS_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt673 ::= ( _OS_KEY ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) ( _OC_KEY ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) )* '}' ) | '{}' ;
_alt675 ::= ( _OS_KEY ( '"reason"' ) ( _OC_KEY ( '"reason"' ) )* '}' ) | '{}' ;
_alt677 ::= ( _OS_KEY ( ( '"hit"' | '"miss"' ) | ( ( '"all"' | JSON_STRING ) | JSON_NULL ) ) ( _OC_KEY ( ( '"hit"' | '"miss"' ) | ( ( '"all"' | JSON_STRING ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt679 ::= ( _OS_KEY ( ( '"hit"' | '"miss"' ) | ( ( '"all"' | JSON_STRING ) | JSON_NULL ) ) ( _OC_KEY ( ( '"hit"' | '"miss"' ) | ( ( '"all"' | JSON_STRING ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt681 ::= ( _OS_KEY ( ( ( '"all"' | JSON_STRING ) | JSON_NULL ) | ( '"hit"' | '"miss"' | '"partial_hit"' | '"status"' ) ) ( _OC_KEY ( ( ( '"all"' | JSON_STRING ) | JSON_NULL ) | ( '"hit"' | '"miss"' | '"partial_hit"' | '"status"' ) ) )* '}' ) | '{}' ;
_alt683 ::= ( _OS_KEY ( '"scope"' | '"no_store"' | '"max_age"' ) ( _OC_KEY ( '"scope"' | '"no_store"' | '"max_age"' ) )* '}' ) | '{}' ;
_alt685 ::= ( _OS_KEY _pv686 ( _OC_KEY _pv686 )* '}' ) | '{}' ;
_alt690 ::= ( _OS_KEY _pv691 ( _OC_KEY _pv691 )* '}' ) | '{}' ;
_alt693 ::= ( _OS_KEY _pv691 ( _OC_KEY _pv691 )* '}' ) | '{}' ;
_alt696 ::= ( _OS_KEY _pv691 ( _OC_KEY _pv691 )* '}' ) | '{}' ;
_alt699 ::= ( _OS_KEY _def598 ( _OC_KEY _def598 )* '}' ) | '{}' ;
_alt701 ::= ( _OS_KEY _pv702 ( _OC_KEY _pv702 )* '}' ) | '{}' ;
_alt704 ::= ( _OS_KEY _pv702 ( _OC_KEY _pv702 )* '}' ) | '{}' ;
_alt707 ::= ( _OS_KEY _def576 ( _OC_KEY _def576 )* '}' ) | '{}' ;
_alt714 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_alt716 ::= ( _OS_KEY ( '"name"' ) ( _OC_KEY ( '"name"' ) )* '}' ) | '{}' ;
_alt718 ::= ( _OS_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt720 ::= ( _OS_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt722 ::= ( _OS_KEY ( '"code"' | '"reason"' ) ( _OC_KEY ( '"code"' | '"reason"' ) )* '}' ) | '{}' ;
_alt724 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_alt726 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_alt728 ::= ( _OS_KEY ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) ( _OC_KEY ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) )* '}' ) | '{}' ;
_alt730 ::= ( _OS_KEY ( '"reason"' ) ( _OC_KEY ( '"reason"' ) )* '}' ) | '{}' ;
_alt732 ::= ( _OS_KEY ( '"problems"' | '"count"' | '"boolean"' ) ( _OC_KEY ( '"problems"' | '"count"' | '"boolean"' ) )* '}' ) | '{}' ;
_alt734 ::= ( _OS_KEY ( '"problems"' | '"count"' | '"boolean"' ) ( _OC_KEY ( '"problems"' | '"count"' | '"boolean"' ) )* '}' ) | '{}' ;
_alt736 ::= ( _OS_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt738 ::= ( _OS_KEY ( ( '"string"' | '"hash"' ) | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( '"string"' | '"hash"' ) | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt740 ::= ( _OS_KEY ( '"string"' ) ( _OC_KEY ( '"string"' ) )* '}' ) | '{}' ;
_alt742 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_alt745 ::= ( _OS_KEY _pv746 ( _OC_KEY _pv746 )* '}' ) | '{}' ;
_alt748 ::= ( _OS_KEY _pv746 ( _OC_KEY _pv746 )* '}' ) | '{}' ;
_alt751 ::= ( _OS_KEY _pv746 ( _OC_KEY _pv746 )* '}' ) | '{}' ;
_alt754 ::= ( _OS_KEY _def604 ( _OC_KEY _def604 )* '}' ) | '{}' ;
_alt756 ::= ( _OS_KEY _pv757 ( _OC_KEY _pv757 )* '}' ) | '{}' ;
_alt759 ::= ( _OS_KEY _pv757 ( _OC_KEY _pv757 )* '}' ) | '{}' ;
_alt762 ::= ( _OS_KEY _def603 ( _OC_KEY _def603 )* '}' ) | '{}' ;
_alt764 ::= ( _OS_KEY ( '"value"' ) ( _OC_KEY ( '"value"' ) )* '}' ) | '{}' ;
_alt766 ::= ( _OS_KEY ( '"string"' ) ( _OC_KEY ( '"string"' ) )* '}' ) | '{}' ;
_alt768 ::= ( _OS_KEY ( '"name"' | '"type"' ) ( _OC_KEY ( '"name"' | '"type"' ) )* '}' ) | '{}' ;
_alt770 ::= ( _OS_KEY ( '"string"' ) ( _OC_KEY ( '"string"' ) )* '}' ) | '{}' ;
_alt772 ::= ( _OS_KEY ( ( '"string"' | '"hash"' ) | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( '"string"' | '"hash"' ) | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_alt774 ::= ( _OS_KEY ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) ( _OC_KEY ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) )* '}' ) | '{}' ;
_alt777 ::= ( _OS_KEY _def354 ( _OC_KEY _def354 )* '}' ) | '{}' ;
_alt779 ::= ( _OS_KEY JSON_STRING ( _OC_KEY JSON_STRING )* '}' ) | '{}' ;
_alt781 ::= ( _OS_KEY _def576 ( _OC_KEY _def576 )* '}' ) | '{}' ;
_alt783 ::= ( _OS_KEY _def216 ( _OC_KEY _def216 )* '}' ) | '{}' ;
_alt785 ::= ( _OS_KEY _def349 ( _OC_KEY _def349 )* '}' ) | '{}' ;
_alt787 ::= ( _OS_KEY _def222 ( _OC_KEY _def222 )* '}' ) | '{}' ;
_def1 ::= ( _OS_KEY ( JSON_BOOL | _def31 | _def30 ) ( _OC_KEY ( JSON_BOOL | _def31 | _def30 ) )* '}' ) | '{}' ;
_def10 ::= ( _OS_KEY ( JSON_STRING | JSON_NULL ) ( _OC_KEY ( JSON_STRING | JSON_NULL ) )* '}' ) | '{}' ;
_def100 ::= ( _OS_KEY ( _json_object | _def190 ) ( _OC_KEY ( _json_object | _def190 ) )* '}' ) | '{}' ;
_def101 ::= ( _OS_KEY JSON_STRING ( _OC_KEY JSON_STRING )* '}' ) | '{}' ;
_def103 ::= ( _OS_KEY ( ( ( '"gzip"' | '"deflate"' | '"br"' | '"identity"' ) | JSON_NULL ) | ( _def194 | JSON_NULL ) | JSON_STRING | ( ( '"enable"' | '"disable"' | '"http2only"' ) | JSON_NULL ) | ( JSON_BOOL | JSON_NULL ) | ( ( '"ipv4_only"' | '"ipv6_only"' | '"ipv4_and_ipv6"' | '"ipv6_then_ipv4"' | '"ipv4_then_ipv6"' ) | JSON_NULL ) ) ( _OC_KEY ( ( ( '"gzip"' | '"deflate"' | '"br"' | '"identity"' ) | JSON_NULL ) | ( _def194 | JSON_NULL ) | JSON_STRING | ( ( '"enable"' | '"disable"' | '"http2only"' ) | JSON_NULL ) | ( JSON_BOOL | JSON_NULL ) | ( ( '"ipv4_only"' | '"ipv6_only"' | '"ipv4_and_ipv6"' | '"ipv6_then_ipv4"' | '"ipv4_then_ipv6"' ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_def104 ::= ( _OS_KEY ( _json_object | ( _def196 | JSON_NULL ) ) ( _OC_KEY ( _json_object | ( _def196 | JSON_NULL ) ) )* '}' ) | '{}' ;
_def105 ::= ( _OS_KEY ( ( _def194 | JSON_NULL ) | JSON_STRING | ( JSON_INTEGER | JSON_NULL ) ) ( _OC_KEY ( ( _def194 | JSON_NULL ) | JSON_STRING | ( JSON_INTEGER | JSON_NULL ) ) )* '}' ) | '{}' ;
_def107 ::= ( _OS_KEY ( _def199 | ( _def200 | JSON_NULL ) ) ( _OC_KEY ( _def199 | ( _def200 | JSON_NULL ) ) )* '}' ) | '{}' ;
_def109 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_def11 ::= ( _OS_KEY ( JSON_BOOL | JSON_STRING | ( JSON_STRING | JSON_STRING ) ) ( _OC_KEY ( JSON_BOOL | JSON_STRING | ( JSON_STRING | JSON_STRING ) ) )* '}' ) | '{}' ;
_def112 ::= ( _OS_KEY ( JSON_BOOL | _pv203 | JSON_STRING | _pv205 | ( '"Continue"' | '"Error"' ) ) ( _OC_KEY ( JSON_BOOL | _pv203 | JSON_STRING | _pv205 | ( '"Continue"' | '"Error"' ) ) )* '}' ) | '{}' ;
_def114 ::= ( _alt208 ) ;
_def116 ::= ( _OS_KEY ( JSON_BOOL | ( '"errors"' | '"extensions"' | '"disabled"' ) ) ( _OC_KEY ( JSON_BOOL | ( '"errors"' | '"extensions"' | '"disabled"' ) ) )* '}' ) | '{}' ;
_def118 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_def12 ::= ( _OS_KEY ( _json_object | ( _def62 | JSON_NULL ) | _def63 ) ( _OC_KEY ( _json_object | ( _def62 | JSON_NULL ) | _def63 ) )* '}' ) | '{}' ;
_def121 ::= ( _OS_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def122 ::= ( _OS_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def124 ::= ( _OS_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | ( _def216 | JSON_NULL ) | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | ( _def216 | JSON_NULL ) | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def125 ::= ( _OS_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | _def216 | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | _def216 | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def127 ::= ( _OS_KEY ( _def219 | _def220 ) ( _OC_KEY ( _def219 | _def220 ) )* '}' ) | '{}' ;
_def129 ::= ( _OS_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | _def222 | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | _def222 | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def13 ::= ( _OS_KEY ( JSON_BOOL | JSON_STRING | _def65 | ( JSON_STRING | JSON_STRING ) ) ( _OC_KEY ( JSON_BOOL | JSON_STRING | _def65 | ( JSON_STRING | JSON_STRING ) ) )* '}' ) | '{}' ;
_def130 ::= ( _OS_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | _def222 | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | _def222 | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def138 ::= ( _OS_KEY ( JSON_STRING | JSON_NULL ) ( _OC_KEY ( JSON_STRING | JSON_NULL ) )* '}' ) | '{}' ;
_def14 ::= ( _OS_KEY ( JSON_BOOL | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_BOOL | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def145 ::= ( _alt226 | _alt231 | _alt234 ) ;
_def148 ::= ( _OS_KEY ( JSON_STRING | JSON_NULL ) ( _OC_KEY ( JSON_STRING | JSON_NULL ) )* '}' ) | '{}' ;
_def15 ::= ( _OS_KEY ( _def68 | _json_object ) ( _OC_KEY ( _def68 | _json_object ) )* '}' ) | '{}' ;
_def16 ::= ( _OS_KEY ( JSON_BOOL | ( JSON_INTEGER | JSON_NULL ) | JSON_INTEGER | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_BOOL | ( JSON_INTEGER | JSON_NULL ) | JSON_INTEGER | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def163 ::= ( _OS_KEY ( ( _def200 | JSON_NULL ) | ( JSON_BOOL | JSON_NULL ) | ( _def238 | JSON_NULL ) | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( _def200 | JSON_NULL ) | ( JSON_BOOL | JSON_NULL ) | ( _def238 | JSON_NULL ) | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def165 ::= ( _OS_KEY ( ( '"stream"' ) | JSON_BOOL | _def240 ) ( _OC_KEY ( ( '"stream"' ) | JSON_BOOL | _def240 ) )* '}' ) | '{}' ;
_def17 ::= ( _OS_KEY ( JSON_BOOL | _def71 | _def74 | _pv72 ) ( _OC_KEY ( JSON_BOOL | _def71 | _def74 | _pv72 ) )* '}' ) | '{}' ;
_def170 ::= ( _OS_KEY ( ( '"disabled"' | '"enabled"' | JSON_STRING ) | ( JSON_STRING | JSON_NULL ) | JSON_STRING | _pv48 | ( ( JSON_STRING | JSON_STRING ) | JSON_NULL ) ) ( _OC_KEY ( ( '"disabled"' | '"enabled"' | JSON_STRING ) | ( JSON_STRING | JSON_NULL ) | JSON_STRING | _pv48 | ( ( JSON_STRING | JSON_STRING ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_def171 ::= ( _OS_KEY ( ( _def244 | JSON_NULL ) | _json_object ) ( _OC_KEY ( ( _def244 | JSON_NULL ) | _json_object ) )* '}' ) | '{}' ;
_def173 ::= ( _OS_KEY ( _def199 | ( _def246 | JSON_NULL ) ) ( _OC_KEY ( _def199 | ( _def246 | JSON_NULL ) ) )* '}' ) | '{}' ;
_def174 ::= ( _OS_KEY ( JSON_BOOL | ( '"measure"' | '"enforce"' ) | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_BOOL | ( '"measure"' | '"enforce"' ) | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def176 ::= ( _OS_KEY ( ( '"disabled"' | '"enabled"' ) | _def249 ) ( _OC_KEY ( ( '"disabled"' | '"enabled"' ) | _def249 ) )* '}' ) | '{}' ;
_def177 ::= ( _OS_KEY ( _def251 | _def252 ) ( _OC_KEY ( _def251 | _def252 ) )* '}' ) | '{}' ;
_def178 ::= ( '"none"' | '"all"' | _alt254 | _alt257 ) ;
_def179 ::= ( '"none"' | '"all"' | _alt260 | _alt263 ) ;
_def18 ::= ( _OS_KEY ( JSON_BOOL | _def76 | _def77 | _def78 ) ( _OC_KEY ( JSON_BOOL | _def76 | _def77 | _def78 ) )* '}' ) | '{}' ;
_def180 ::= ( _OS_KEY _def266 ( _OC_KEY _def266 )* '}' ) | '{}' ;
_def182 ::= ( _OS_KEY ( _def268 | _def269 ) ( _OC_KEY ( _def268 | _def269 ) )* '}' ) | '{}' ;
_def183 ::= ( _OS_KEY ( _def273 | _def272 | _def271 ) ( _OC_KEY ( _def273 | _def272 | _def271 ) )* '}' ) | '{}' ;
_def184 ::= ( _OS_KEY ( _def279 | _def275 | _def277 | _def278 | _def272 | _def276 ) ( _OC_KEY ( _def279 | _def275 | _def277 | _def278 | _def272 | _def276 ) )* '}' ) | '{}' ;
_def186 ::= ( _OS_KEY ( _def284 | _def282 | _def281 | _def283 ) ( _OC_KEY ( _def284 | _def282 | _def281 | _def283 ) )* '}' ) | '{}' ;
_def187 ::= ( _OS_KEY ( _def287 | _def288 | _def290 | _def291 | _def286 | ( '"none"' | '"required"' | '"recommended"' ) | _def289 ) ( _OC_KEY ( _def287 | _def288 | _def290 | _def291 | _def286 | ( '"none"' | '"required"' | '"recommended"' ) | _def289 ) )* '}' ) | '{}' ;
_def188 ::= ( _OS_KEY ( _def295 | ( '"deprecated"' | '"spec_compliant"' ) | _def293 | _def296 | _def297 | _def294 | ( '"none"' | '"required"' | '"recommended"' ) ) ( _OC_KEY ( _def295 | ( '"deprecated"' | '"spec_compliant"' ) | _def293 | _def296 | _def297 | _def294 | ( '"none"' | '"required"' | '"recommended"' ) ) )* '}' ) | '{}' ;
_def19 ::= ( _OS_KEY ( JSON_BOOL | ( _def80 | JSON_NULL ) | _def82 | _def81 ) ( _OC_KEY ( JSON_BOOL | ( _def80 | JSON_NULL ) | _def82 | _def81 ) )* '}' ) | '{}' ;
_def190 ::= ( _OS_KEY ( ( _def299 | JSON_NULL ) | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( _def299 | JSON_NULL ) | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def194 ::= ( _OS_KEY ( JSON_STRING | JSON_INTEGER ) ( _OC_KEY ( JSON_STRING | JSON_INTEGER ) )* '}' ) | '{}' ;
_def196 ::= ( _OS_KEY ( ( ( '"gzip"' | '"deflate"' | '"br"' | '"identity"' ) | JSON_NULL ) | ( _def194 | JSON_NULL ) | JSON_STRING | ( ( '"enable"' | '"disable"' | '"http2only"' ) | JSON_NULL ) | ( ( '"ipv4_only"' | '"ipv6_only"' | '"ipv4_and_ipv6"' | '"ipv6_then_ipv4"' | '"ipv4_then_ipv6"' ) | JSON_NULL ) ) ( _OC_KEY ( ( ( '"gzip"' | '"deflate"' | '"br"' | '"identity"' ) | JSON_NULL ) | ( _def194 | JSON_NULL ) | JSON_STRING | ( ( '"enable"' | '"disable"' | '"http2only"' ) | JSON_NULL ) | ( ( '"ipv4_only"' | '"ipv6_only"' | '"ipv4_and_ipv6"' | '"ipv6_then_ipv4"' | '"ipv4_then_ipv6"' ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_def199 ::= ( _OS_KEY JSON_INTEGER ( _OC_KEY JSON_INTEGER )* '}' ) | '{}' ;
_def2 ::= ( _OS_KEY ( ( _def35 | JSON_NULL ) | ( _def34 | JSON_NULL ) | ( _def33 | JSON_NULL ) ) ( _OC_KEY ( ( _def35 | JSON_NULL ) | ( _def34 | JSON_NULL ) | ( _def33 | JSON_NULL ) ) )* '}' ) | '{}' ;
_def20 ::= ( _OS_KEY ( JSON_BOOL | _def84 ) ( _OC_KEY ( JSON_BOOL | _def84 ) )* '}' ) | '{}' ;
_def200 ::= ( _OS_KEY ( JSON_BOOL | ( JSON_STRING | JSON_NULL ) | _pv48 | ( _def190 | JSON_NULL ) | JSON_INTEGER ) ( _OC_KEY ( JSON_BOOL | ( JSON_STRING | JSON_NULL ) | _pv48 | ( _def190 | JSON_NULL ) | JSON_INTEGER ) )* '}' ) | '{}' ;
_def204 ::= ( _OS_KEY ( _pv312 | _pv310 | _pv306 | JSON_STRING | _pv308 ) ( _OC_KEY ( _pv312 | _pv310 | _pv306 | JSON_STRING | _pv308 ) )* '}' ) | '{}' ;
_def206 ::= ( _alt315 | _alt317 ) ;
_def209 ::= ( _alt319 | _alt322 ) ;
_def21 ::= ( _OS_KEY ( JSON_STRING | JSON_NULL ) ( _OC_KEY ( JSON_STRING | JSON_NULL ) )* '}' ) | '{}' ;
_def213 ::= ( '"all"' | '"deprecated"' | _alt325 ) ;
_def216 ::= ( _alt328 | _alt333 | _alt336 | _alt339 | _alt341 | _alt344 | _alt347 | '"true"' | '"false"' ) ;
_def219 ::= ( _OS_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | _def349 | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | _def349 | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def22 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_def220 ::= ( _OS_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | _def349 | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( JSON_BOOL | _def213 ) | JSON_BOOL | _def349 | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def222 ::= ( _alt352 | _alt356 | _alt359 | _alt362 | _alt364 | _alt367 | _alt370 | '"true"' | '"false"' ) ;
_def227 ::= ( _OS_KEY JSON_STRING ( _OC_KEY JSON_STRING )* '}' ) | '{}' ;
_def228 ::= ( _OS_KEY JSON_STRING ( _OC_KEY JSON_STRING )* '}' ) | '{}' ;
_def229 ::= ( _OS_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def23 ::= ( _OS_KEY _def88 ( _OC_KEY _def88 )* '}' ) | '{}' ;
_def232 ::= ( _alt375 | _alt377 ) ;
_def235 ::= ( _alt379 | _alt381 ) ;
_def238 ::= ( _OS_KEY ( JSON_BOOL | JSON_STRING ) ( _OC_KEY ( JSON_BOOL | JSON_STRING ) )* '}' ) | '{}' ;
_def24 ::= ( _OS_KEY ( JSON_BOOL | _def91 | ( JSON_INTEGER | JSON_NULL ) | _def90 ) ( _OC_KEY ( JSON_BOOL | _def91 | ( JSON_INTEGER | JSON_NULL ) | _def90 ) )* '}' ) | '{}' ;
_def240 ::= ( _OS_KEY ( JSON_STRING | JSON_INTEGER ) ( _OC_KEY ( JSON_STRING | JSON_INTEGER ) )* '}' ) | '{}' ;
_def244 ::= ( _OS_KEY ( ( '"graphql_ws"' | '"graphql_transport_ws"' ) | ( '"disabled"' | '"enabled"' | JSON_STRING ) | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( '"graphql_ws"' | '"graphql_transport_ws"' ) | ( '"disabled"' | '"enabled"' | JSON_STRING ) | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def246 ::= ( _OS_KEY ( JSON_BOOL | ( JSON_STRING | JSON_NULL ) | _pv48 | ( _def190 | JSON_NULL ) | JSON_INTEGER ) ( _OC_KEY ( JSON_BOOL | ( JSON_STRING | JSON_NULL ) | _pv48 | ( _def190 | JSON_NULL ) | JSON_INTEGER ) )* '}' ) | '{}' ;
_def249 ::= ( _OS_KEY ( _def388 | _json_object ) ( _OC_KEY ( _def388 | _json_object ) )* '}' ) | '{}' ;
_def25 ::= ( _OS_KEY ( JSON_BOOL | JSON_STRING | _def93 | ( JSON_STRING | JSON_STRING ) ) ( _OC_KEY ( JSON_BOOL | JSON_STRING | _def93 | ( JSON_STRING | JSON_STRING ) ) )* '}' ) | '{}' ;
_def251 ::= ( _OS_KEY _def390 ( _OC_KEY _def390 )* '}' ) | '{}' ;
_def252 ::= ( _OS_KEY _def392 ( _OC_KEY _def392 )* '}' ) | '{}' ;
_def26 ::= ( _OS_KEY ( _def96 | _def97 | _def95 ) ( _OC_KEY ( _def96 | _def97 | _def95 ) )* '}' ) | '{}' ;
_def266 ::= ( _OS_KEY ( JSON_STRING | JSON_INTEGER ) ( _OC_KEY ( JSON_STRING | JSON_INTEGER ) )* '}' ) | '{}' ;
_def268 ::= ( _OS_KEY ( _json_object | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( _json_object | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def269 ::= ( _OS_KEY ( JSON_BOOL | ( _def396 | JSON_NULL ) | _def397 | _def396 ) ( _OC_KEY ( JSON_BOOL | ( _def396 | JSON_NULL ) | _def397 | _def396 ) )* '}' ) | '{}' ;
_def27 ::= ( _OS_KEY ( _def100 | _def99 | ( _def101 | JSON_NULL ) ) ( _OC_KEY ( _def100 | _def99 | ( _def101 | JSON_NULL ) ) )* '}' ) | '{}' ;
_def271 ::= ( _OS_KEY ( _pv399 | _json_object | _pv400 | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( _pv399 | _json_object | _pv400 | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def272 ::= ( _OS_KEY ( JSON_BOOL | _def404 | _def403 | _def266 | ( '"grpc"' | '"http"' ) | ( JSON_STRING | JSON_NULL ) | ( '"cumulative"' | '"delta"' ) ) ( _OC_KEY ( JSON_BOOL | _def404 | _def403 | _def266 | ( '"grpc"' | '"http"' ) | ( JSON_STRING | JSON_NULL ) | ( '"cumulative"' | '"delta"' ) ) )* '}' ) | '{}' ;
_def273 ::= ( _OS_KEY ( JSON_BOOL | JSON_STRING | ( '"all"' | '"none"' ) | ( JSON_STRING | JSON_STRING ) ) ( _OC_KEY ( JSON_BOOL | JSON_STRING | ( '"all"' | '"none"' ) | ( JSON_STRING | JSON_STRING ) ) )* '}' ) | '{}' ;
_def275 ::= ( _OS_KEY ( JSON_BOOL | _json_object | ( JSON_NUMBER | ( '"always_on"' | '"always_off"' ) ) | ( JSON_STRING | JSON_NULL ) | ( JSON_BOOL | JSON_NULL ) | JSON_INTEGER ) ( _OC_KEY ( JSON_BOOL | _json_object | ( JSON_NUMBER | ( '"always_on"' | '"always_off"' ) ) | ( JSON_STRING | JSON_NULL ) | ( JSON_BOOL | JSON_NULL ) | JSON_INTEGER ) )* '}' ) | '{}' ;
_def276 ::= ( _OS_KEY ( _def266 | _json_object | JSON_STRING | JSON_BOOL ) ( _OC_KEY ( _def266 | _json_object | JSON_STRING | JSON_BOOL ) )* '}' ) | '{}' ;
_def277 ::= ( _OS_KEY ( ( '"hexadecimal"' | '"open_telemetry"' | '"decimal"' | '"datadog"' | '"uuid"' ) | JSON_BOOL | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( '"hexadecimal"' | '"open_telemetry"' | '"decimal"' | '"datadog"' | '"uuid"' ) | JSON_BOOL | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def278 ::= ( _OS_KEY ( JSON_BOOL | _def410 ) ( _OC_KEY ( JSON_BOOL | _def410 ) )* '}' ) | '{}' ;
_def279 ::= ( _OS_KEY ( _def266 | JSON_STRING | JSON_BOOL ) ( _OC_KEY ( _def266 | JSON_STRING | JSON_BOOL ) )* '}' ) | '{}' ;
_def28 ::= ( _OS_KEY ( _json_object | _def104 | ( _def105 | JSON_NULL ) | ( _def103 | JSON_NULL ) | ( JSON_BOOL | JSON_NULL ) ) ( _OC_KEY ( _json_object | _def104 | ( _def105 | JSON_NULL ) | ( _def103 | JSON_NULL ) | ( JSON_BOOL | JSON_NULL ) ) )* '}' ) | '{}' ;
_def281 ::= ( _OS_KEY _def413 ( _OC_KEY _def413 )* '}' ) | '{}' ;
_def282 ::= ( _OS_KEY _def416 ( _OC_KEY _def416 )* '}' ) | '{}' ;
_def283 ::= ( _OS_KEY _def419 ( _OC_KEY _def419 )* '}' ) | '{}' ;
_def284 ::= ( _OS_KEY _def422 ( _OC_KEY _def422 )* '}' ) | '{}' ;
_def286 ::= ( _OS_KEY _def425 ( _OC_KEY _def425 )* '}' ) | '{}' ;
_def287 ::= ( _OS_KEY _def428 ( _OC_KEY _def428 )* '}' ) | '{}' ;
_def288 ::= ( _OS_KEY _def431 ( _OC_KEY _def431 )* '}' ) | '{}' ;
_def289 ::= ( _OS_KEY ( _def434 | _def435 | _def436 ) ( _OC_KEY ( _def434 | _def435 | _def436 ) )* '}' ) | '{}' ;
_def290 ::= ( _OS_KEY _def439 ( _OC_KEY _def439 )* '}' ) | '{}' ;
_def291 ::= ( _OS_KEY _def442 ( _OC_KEY _def442 )* '}' ) | '{}' ;
_def293 ::= ( _OS_KEY _def445 ( _OC_KEY _def445 )* '}' ) | '{}' ;
_def294 ::= ( _OS_KEY _json_object ( _OC_KEY _json_object )* '}' ) | '{}' ;
_def295 ::= ( _OS_KEY _def448 ( _OC_KEY _def448 )* '}' ) | '{}' ;
_def296 ::= ( _OS_KEY _def450 ( _OC_KEY _def450 )* '}' ) | '{}' ;
_def297 ::= ( _OS_KEY _def452 ( _OC_KEY _def452 )* '}' ) | '{}' ;
_def299 ::= ( _OS_KEY JSON_STRING ( _OC_KEY JSON_STRING )* '}' ) | '{}' ;
_def3 ::= ( _OS_KEY ( JSON_BOOL | _def37 ) ( _OC_KEY ( JSON_BOOL | _def37 ) )* '}' ) | '{}' ;
_def30 ::= ( _OS_KEY _def107 ( _OC_KEY _def107 )* '}' ) | '{}' ;
_def31 ::= ( _OS_KEY ( _def109 | _json_object ) ( _OC_KEY ( _def109 | _json_object ) )* '}' ) | '{}' ;
_def311 ::= ( _OS_KEY JSON_STRING ( _OC_KEY JSON_STRING )* '}' ) | '{}' ;
_def320 ::= ( _OS_KEY ( JSON_STRING | ( _def456 | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( _def456 | JSON_NULL ) ) )* '}' ) | '{}' ;
_def323 ::= ( _OS_KEY ( ( JSON_STRING | JSON_NULL ) | JSON_STRING | ( _def456 | JSON_NULL ) ) ( _OC_KEY ( ( JSON_STRING | JSON_NULL ) | JSON_STRING | ( _def456 | JSON_NULL ) ) )* '}' ) | '{}' ;
_def33 ::= ( _OS_KEY _json_object ( _OC_KEY _json_object )* '}' ) | '{}' ;
_def330 ::= ( _alt459 | _alt460 | _pv399 | _pv48 ) ;
_def331 ::= ( _alt463 | _alt465 | _alt467 | _alt469 | _alt471 | _alt473 | _alt475 | _alt477 | _alt479 | _alt481 | _alt483 | _alt485 | _alt487 | _alt489 | _alt491 | JSON_STRING | _alt493 | _alt495 | _alt497 ) ;
_def34 ::= ( _OS_KEY _def112 ( _OC_KEY _def112 )* '}' ) | '{}' ;
_def349 ::= ( _alt499 | _alt503 | _alt506 | _alt509 | _alt511 | _alt514 | _alt517 | '"true"' | '"false"' ) ;
_def35 ::= ( _OS_KEY ( ( _def114 | JSON_NULL ) | _json_object ) ( _OC_KEY ( ( _def114 | JSON_NULL ) | _json_object ) )* '}' ) | '{}' ;
_def354 ::= ( _alt519 | _alt521 | _alt523 | _alt525 | _alt527 | _alt529 | _alt531 | _alt533 | _alt535 | _alt537 | _alt539 | _alt541 | _alt543 | JSON_STRING | _alt545 | _alt547 | _alt549 | _alt551 | _alt553 ) ;
_def37 ::= ( _OS_KEY ( JSON_BOOL | _def116 ) ( _OC_KEY ( JSON_BOOL | _def116 ) )* '}' ) | '{}' ;
_def388 ::= ( _OS_KEY ( JSON_BOOL | ( '"strict"' | '"extended"' ) ) ( _OC_KEY ( JSON_BOOL | ( '"strict"' | '"extended"' ) ) )* '}' ) | '{}' ;
_def39 ::= ( _OS_KEY ( _json_object | _def118 ) ( _OC_KEY ( _json_object | _def118 ) )* '}' ) | '{}' ;
_def390 ::= ( _OS_KEY JSON_STRING ( _OC_KEY JSON_STRING )* '}' ) | '{}' ;
_def392 ::= ( _OS_KEY ( JSON_STRING | JSON_INTEGER ) ( _OC_KEY ( JSON_STRING | JSON_INTEGER ) )* '}' ) | '{}' ;
_def396 ::= ( _alt558 | '"json"' | _alt563 | '"text"' ) ;
_def397 ::= ( _OS_KEY ( JSON_BOOL | JSON_STRING | JSON_INTEGER ) ( _OC_KEY ( JSON_BOOL | JSON_STRING | JSON_INTEGER ) )* '}' ) | '{}' ;
_def4 ::= ( _OS_KEY ( ( _def39 | JSON_NULL ) | JSON_BOOL | ( '"batch_http_link"' ) | ( JSON_INTEGER | JSON_NULL ) ) ( _OC_KEY ( ( _def39 | JSON_NULL ) | JSON_BOOL | ( '"batch_http_link"' ) | ( JSON_INTEGER | JSON_NULL ) ) )* '}' ) | '{}' ;
_def401 ::= ( _OS_KEY ( ( _def568 | JSON_NULL ) | _pv569 | JSON_STRING | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( ( _def568 | JSON_NULL ) | _pv569 | JSON_STRING | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def403 ::= ( _OS_KEY ( _json_object | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( _json_object | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def404 ::= ( _OS_KEY _json_object ( _OC_KEY _json_object )* '}' ) | '{}' ;
_def410 ::= ( _OS_KEY ( ( '"hexadecimal"' | '"open_telemetry"' | '"decimal"' | '"datadog"' | '"uuid"' ) | JSON_STRING ) ( _OC_KEY ( ( '"hexadecimal"' | '"open_telemetry"' | '"decimal"' | '"datadog"' | '"uuid"' ) | JSON_STRING ) )* '}' ) | '{}' ;
_def413 ::= ( ( '"info"' | '"warn"' | '"error"' | '"off"' ) | _alt575 ) ;
_def414 ::= ( _OS_KEY ( ( '"request"' | '"response"' | '"event_response"' | '"error"' ) | _def578 | _def576 | JSON_STRING | ( '"info"' | '"warn"' | '"error"' | '"off"' ) ) ( _OC_KEY ( ( '"request"' | '"response"' | '"event_response"' | '"error"' ) | _def578 | _def576 | JSON_STRING | ( '"info"' | '"warn"' | '"error"' | '"off"' ) ) )* '}' ) | '{}' ;
_def416 ::= ( ( '"info"' | '"warn"' | '"error"' | '"off"' ) | _alt580 ) ;
_def417 ::= ( _OS_KEY ( _def216 | ( '"request"' | '"response"' | '"event_response"' | '"error"' ) | _def582 | JSON_STRING | ( '"info"' | '"warn"' | '"error"' | '"off"' ) ) ( _OC_KEY ( _def216 | ( '"request"' | '"response"' | '"event_response"' | '"error"' ) | _def582 | JSON_STRING | ( '"info"' | '"warn"' | '"error"' | '"off"' ) ) )* '}' ) | '{}' ;
_def419 ::= ( ( '"info"' | '"warn"' | '"error"' | '"off"' ) | _alt584 ) ;
_def42 ::= ( _OS_KEY ( ( ( '"enable"' | '"disable"' | '"http2only"' ) | JSON_NULL ) | ( ( '"ipv4_only"' | '"ipv6_only"' | '"ipv4_and_ipv6"' | '"ipv6_then_ipv4"' | '"ipv4_then_ipv6"' ) | JSON_NULL ) ) ( _OC_KEY ( ( ( '"enable"' | '"disable"' | '"http2only"' ) | JSON_NULL ) | ( ( '"ipv4_only"' | '"ipv6_only"' | '"ipv4_and_ipv6"' | '"ipv6_then_ipv4"' | '"ipv4_then_ipv6"' ) | JSON_NULL ) ) )* '}' ) | '{}' ;
_def420 ::= ( _OS_KEY ( ( '"request"' | '"response"' | '"event_response"' | '"error"' ) | JSON_STRING | ( '"info"' | '"warn"' | '"error"' | '"off"' ) | _def349 | _def586 ) ( _OC_KEY ( ( '"request"' | '"response"' | '"event_response"' | '"error"' ) | JSON_STRING | ( '"info"' | '"warn"' | '"error"' | '"off"' ) | _def349 | _def586 ) )* '}' ) | '{}' ;
_def422 ::= ( ( '"info"' | '"warn"' | '"error"' | '"off"' ) | _alt588 ) ;
_def423 ::= ( _OS_KEY ( _def222 | ( '"request"' | '"response"' | '"event_response"' | '"error"' ) | JSON_STRING | ( '"info"' | '"warn"' | '"error"' | '"off"' ) | _def590 ) ( _OC_KEY ( _def222 | ( '"request"' | '"response"' | '"event_response"' | '"error"' ) | JSON_STRING | ( '"info"' | '"warn"' | '"error"' | '"off"' ) | _def590 ) )* '}' ) | '{}' ;
_def425 ::= ( JSON_NULL | JSON_BOOL | _alt592 ) ;
_def426 ::= ( _OS_KEY ( ( '"counter"' | '"histogram"' ) | ( ( '"duration"' | '"unit"' ) | _def501 ) | JSON_STRING | _def349 | _def593 ) ( _OC_KEY ( ( '"counter"' | '"histogram"' ) | ( ( '"duration"' | '"unit"' ) | _def501 ) | JSON_STRING | _def349 | _def593 ) )* '}' ) | '{}' ;
_def428 ::= ( JSON_NULL | JSON_BOOL | _alt596 ) ;
_def429 ::= ( _OS_KEY ( ( '"counter"' | '"histogram"' ) | _def578 | _def576 | ( ( '"duration"' | '"unit"' ) | _def598 ) | JSON_STRING ) ( _OC_KEY ( ( '"counter"' | '"histogram"' ) | _def578 | _def576 | ( ( '"duration"' | '"unit"' ) | _def598 ) | JSON_STRING ) )* '}' ) | '{}' ;
_def43 ::= ( _OS_KEY ( _def121 | _def122 ) ( _OC_KEY ( _def121 | _def122 ) )* '}' ) | '{}' ;
_def431 ::= ( JSON_NULL | JSON_BOOL | _alt600 ) ;
_def432 ::= ( _OS_KEY ( _def603 | ( '"unit"' | _def604 ) | ( '"counter"' | '"histogram"' ) | _def601 | JSON_STRING ) ( _OC_KEY ( _def603 | ( '"unit"' | _def604 ) | ( '"counter"' | '"histogram"' ) | _def601 | JSON_STRING ) )* '}' ) | '{}' ;
_def434 ::= ( JSON_NULL | JSON_BOOL | _alt606 ) ;
_def435 ::= ( JSON_NULL | JSON_BOOL | _alt608 ) ;
_def436 ::= ( JSON_NULL | JSON_BOOL | _alt611 ) ;
_def437 ::= ( _OS_KEY ( _def216 | ( '"counter"' | '"histogram"' ) | _def582 | ( ( '"duration"' | '"unit"' ) | _def331 ) | JSON_STRING ) ( _OC_KEY ( _def216 | ( '"counter"' | '"histogram"' ) | _def582 | ( ( '"duration"' | '"unit"' ) | _def331 ) | JSON_STRING ) )* '}' ) | '{}' ;
_def439 ::= ( JSON_NULL | JSON_BOOL | _alt614 ) ;
_def44 ::= ( _OS_KEY ( _def124 | _def125 ) ( _OC_KEY ( _def124 | _def125 ) )* '}' ) | '{}' ;
_def440 ::= ( _OS_KEY ( ( '"counter"' | '"histogram"' ) | ( ( '"duration"' | '"unit"' ) | _def501 ) | JSON_STRING | _def349 | _def586 ) ( _OC_KEY ( ( '"counter"' | '"histogram"' ) | ( ( '"duration"' | '"unit"' ) | _def501 ) | JSON_STRING | _def349 | _def586 ) )* '}' ) | '{}' ;
_def442 ::= ( JSON_NULL | JSON_BOOL | _alt617 ) ;
_def443 ::= ( _OS_KEY ( _def222 | ( '"counter"' | '"histogram"' ) | JSON_STRING | ( ( '"duration"' | '"unit"' ) | _def619 | _def354 ) | _def590 ) ( _OC_KEY ( _def222 | ( '"counter"' | '"histogram"' ) | JSON_STRING | ( ( '"duration"' | '"unit"' ) | _def619 | _def354 ) | _def590 ) )* '}' ) | '{}' ;
_def445 ::= ( _OS_KEY ( _def621 | JSON_NULL ) ( _OC_KEY ( _def621 | JSON_NULL ) )* '}' ) | '{}' ;
_def448 ::= ( _OS_KEY ( ( _def621 | JSON_NULL ) | ( JSON_BOOL | JSON_NULL ) ) ( _OC_KEY ( ( _def621 | JSON_NULL ) | ( JSON_BOOL | JSON_NULL ) ) )* '}' ) | '{}' ;
_def45 ::= ( _OS_KEY _def127 ( _OC_KEY _def127 )* '}' ) | '{}' ;
_def450 ::= ( _OS_KEY ( _def621 | JSON_NULL ) ( _OC_KEY ( _def621 | JSON_NULL ) )* '}' ) | '{}' ;
_def452 ::= ( _OS_KEY ( _def621 | JSON_NULL ) ( _OC_KEY ( _def621 | JSON_NULL ) )* '}' ) | '{}' ;
_def456 ::= ( _OS_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_STRING | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def46 ::= ( _OS_KEY ( _def129 | _def130 ) ( _OC_KEY ( _def129 | _def130 ) )* '}' ) | '{}' ;
_def5 ::= ( _OS_KEY ( JSON_BOOL | ( JSON_BOOL | JSON_NULL ) | _json_object | ( JSON_INTEGER | JSON_NULL ) ) ( _OC_KEY ( JSON_BOOL | ( JSON_BOOL | JSON_NULL ) | _json_object | ( JSON_INTEGER | JSON_NULL ) ) )* '}' ) | '{}' ;
_def501 ::= ( _alt631 | _alt633 | _alt635 | _alt637 | _alt639 | _alt641 | _alt643 | _alt645 | _alt647 | _alt649 | _alt651 | _alt653 | _alt655 | _alt657 | _alt659 | _alt661 | _alt663 | _alt665 | _alt667 | _alt669 | _alt671 | JSON_STRING | _alt673 | _alt675 | _alt677 | _alt679 | _alt681 | _alt683 ) ;
_def54 ::= ( _OS_KEY ( _pv135 | ( _def138 | JSON_NULL ) | JSON_STRING | ( JSON_BOOL | JSON_NULL ) | _pv48 ) ( _OC_KEY ( _pv135 | ( _def138 | JSON_NULL ) | JSON_STRING | ( JSON_BOOL | JSON_NULL ) | _pv48 ) )* '}' ) | '{}' ;
_def568 ::= ( _alt685 | '"drop"' ) ;
_def576 ::= ( _alt690 | _alt693 | _alt696 | _alt699 | _alt701 | _alt704 | _alt707 | '"true"' | '"false"' ) ;
_def578 ::= ( _OS_KEY ( _def621 | JSON_NULL ) ( _OC_KEY ( _def621 | JSON_NULL ) )* '}' ) | '{}' ;
_def58 ::= ( _alt140 ) ;
_def582 ::= ( _OS_KEY ( ( _def621 | JSON_NULL ) | ( JSON_BOOL | JSON_NULL ) ) ( _OC_KEY ( ( _def621 | JSON_NULL ) | ( JSON_BOOL | JSON_NULL ) ) )* '}' ) | '{}' ;
_def586 ::= ( _OS_KEY ( _def621 | JSON_NULL ) ( _OC_KEY ( _def621 | JSON_NULL ) )* '}' ) | '{}' ;
_def590 ::= ( _OS_KEY ( _def621 | JSON_NULL ) ( _OC_KEY ( _def621 | JSON_NULL ) )* '}' ) | '{}' ;
_def593 ::= ( _OS_KEY ( _def621 | JSON_NULL ) ( _OC_KEY ( _def621 | JSON_NULL ) )* '}' ) | '{}' ;
_def598 ::= ( _alt714 | _alt716 | _alt718 | _alt720 | _alt722 | _alt724 | _alt726 | _alt728 | _alt730 | _alt732 | _alt734 | _alt736 | _alt738 | _alt740 | _alt742 ) ;
_def6 ::= ( _OS_KEY ( JSON_BOOL | _def43 | _def44 | ( _def42 | JSON_NULL ) | JSON_STRING | _def46 | _def45 ) ( _OC_KEY ( JSON_BOOL | _def43 | _def44 | ( _def42 | JSON_NULL ) | JSON_STRING | _def46 | _def45 ) )* '}' ) | '{}' ;
_def601 ::= ( _OS_KEY ( _def621 | JSON_NULL ) ( _OC_KEY ( _def621 | JSON_NULL ) )* '}' ) | '{}' ;
_def603 ::= ( _alt745 | _alt748 | _alt751 | _alt754 | _alt756 | _alt759 | _alt762 | '"true"' | '"false"' ) ;
_def604 ::= ( _alt764 | _alt766 | _alt768 | _alt770 | _alt772 | _alt774 ) ;
_def609 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_def619 ::= ( '"event_duration"' | '"event_unit"' | _alt777 ) ;
_def62 ::= ( _OS_KEY _pv144 ( _OC_KEY _pv144 )* '}' ) | '{}' ;
_def621 ::= ( JSON_BOOL | _alt779 ) ;
_def622 ::= ( _def598 | _alt781 ) ;
_def624 ::= ( _def331 | _alt783 ) ;
_def626 ::= ( _def501 | _alt785 ) ;
_def628 ::= ( _def354 | _alt787 ) ;
_def63 ::= ( _OS_KEY ( _json_object | ( _def62 | JSON_NULL ) ) ( _OC_KEY ( _json_object | ( _def62 | JSON_NULL ) ) )* '}' ) | '{}' ;
_def65 ::= ( _OS_KEY ( _def148 | JSON_INTEGER ) ( _OC_KEY ( _def148 | JSON_INTEGER ) )* '}' ) | '{}' ;
_def68 ::= ( JSON_BOOL | _alt150 | _alt153 ) ;
_def7 ::= ( _OS_KEY ( JSON_BOOL | JSON_STRING | _pv48 | _pv52 | _pv49 ) ( _OC_KEY ( JSON_BOOL | JSON_STRING | _pv48 | _pv52 | _pv49 ) )* '}' ) | '{}' ;
_def71 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_def74 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_def76 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_def77 ::= ( _OS_KEY ( JSON_BOOL | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_BOOL | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def78 ::= ( _OS_KEY JSON_BOOL ( _OC_KEY JSON_BOOL )* '}' ) | '{}' ;
_def8 ::= ( _OS_KEY ( JSON_BOOL | _pv48 ) ( _OC_KEY ( JSON_BOOL | _pv48 ) )* '}' ) | '{}' ;
_def80 ::= ( _OS_KEY ( JSON_STRING | JSON_INTEGER | ( JSON_STRING | JSON_STRING ) ) ( _OC_KEY ( JSON_STRING | JSON_INTEGER | ( JSON_STRING | JSON_STRING ) ) )* '}' ) | '{}' ;
_def81 ::= ( _OS_KEY ( JSON_BOOL | ( JSON_STRING | JSON_NULL ) ) ( _OC_KEY ( JSON_BOOL | ( JSON_STRING | JSON_NULL ) ) )* '}' ) | '{}' ;
_def82 ::= ( _OS_KEY ( _json_object | _def163 ) ( _OC_KEY ( _json_object | _def163 ) )* '}' ) | '{}' ;
_def84 ::= ( _OS_KEY _def165 ( _OC_KEY _def165 )* '}' ) | '{}' ;
_def88 ::= ( _OS_KEY JSON_STRING ( _OC_KEY JSON_STRING )* '}' ) | '{}' ;
_def9 ::= ( _OS_KEY ( JSON_BOOL | ( '"measure"' | '"enforce"' ) | _def58 ) ( _OC_KEY ( JSON_BOOL | ( '"measure"' | '"enforce"' ) | _def58 ) )* '}' ) | '{}' ;
_def90 ::= ( _OS_KEY ( JSON_BOOL | _pv48 ) ( _OC_KEY ( JSON_BOOL | _pv48 ) )* '}' ) | '{}' ;
_def91 ::= ( _OS_KEY ( ( _def170 | JSON_NULL ) | ( _def171 | JSON_NULL ) ) ( _OC_KEY ( ( _def170 | JSON_NULL ) | ( _def171 | JSON_NULL ) ) )* '}' ) | '{}' ;
_def93 ::= ( _OS_KEY ( _def174 | ( JSON_INTEGER | JSON_NULL ) | JSON_BOOL | _def173 ) ( _OC_KEY ( _def174 | ( JSON_INTEGER | JSON_NULL ) | JSON_BOOL | _def173 ) )* '}' ) | '{}' ;
_def95 ::= ( _OS_KEY ( JSON_BOOL | _def178 | ( '"grpc"' | '"http"' ) | ( JSON_NUMBER | ( '"always_on"' | '"always_off"' ) ) | ( '"extended"' | '"standard"' ) | _def180 | ( JSON_STRING | JSON_NULL ) | ( '"legacy"' | '"enhanced"' ) | _def179 | _def176 | JSON_STRING | _def177 | JSON_INTEGER ) ( _OC_KEY ( JSON_BOOL | _def178 | ( '"grpc"' | '"http"' ) | ( JSON_NUMBER | ( '"always_on"' | '"always_off"' ) ) | ( '"extended"' | '"standard"' ) | _def180 | ( JSON_STRING | JSON_NULL ) | ( '"legacy"' | '"enhanced"' ) | _def179 | _def176 | JSON_STRING | _def177 | JSON_INTEGER ) )* '}' ) | '{}' ;
_def96 ::= ( _OS_KEY ( _def184 | _def182 | _def183 ) ( _OC_KEY ( _def184 | _def182 | _def183 ) )* '}' ) | '{}' ;
_def97 ::= ( _OS_KEY ( _def186 | _def188 | _def187 ) ( _OC_KEY ( _def186 | _def188 | _def187 ) )* '}' ) | '{}' ;
_def99 ::= ( _OS_KEY ( _json_object | _def190 ) ( _OC_KEY ( _json_object | _def190 ) )* '}' ) | '{}' ;
_pv135 ::= ( _pv48 | JSON_NULL ) ;
_pv141 ::= ( _OS_KEY ( JSON_NUMBER | JSON_INTEGER ) ( _OC_KEY ( JSON_NUMBER | JSON_INTEGER ) )* '}' ) | '{}' ;
_pv144 ::= '[' ( _def145 ( ',' _def145 )* )? ']' ;
_pv203 ::= '[' ( _def204 ( ',' _def204 )* )? ']' ;
_pv205 ::= '[' ( _def206 ( ',' _def206 )* )? ']' ;
_pv306 ::= ( _pv48 | JSON_NULL ) ;
_pv308 ::= ( _pv48 | JSON_NULL ) ;
_pv310 ::= '[' ( _def311 ( ',' _def311 )* )? ']' ;
_pv312 ::= ( _pv48 | JSON_NULL ) ;
_pv329 ::= '[' ( ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | _def331 ) ( ',' ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | _def331 ) )* )? ']' ;
_pv342 ::= '[' ( _def216 ( ',' _def216 )* )? ']' ;
_pv353 ::= '[' ( ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | _def354 ) ( ',' ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | _def354 ) )* )? ']' ;
_pv365 ::= '[' ( _def222 ( ',' _def222 )* )? ']' ;
_pv399 ::= '[' ( JSON_NUMBER ( ',' JSON_NUMBER )* )? ']' ;
_pv400 ::= '[' ( _def401 ( ',' _def401 )* )? ']' ;
_pv48 ::= '[' ( JSON_STRING ( ',' JSON_STRING )* )? ']' ;
_pv49 ::= ( _pv48 | JSON_NULL ) ;
_pv500 ::= '[' ( ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | _def501 ) ( ',' ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | _def501 ) )* )? ']' ;
_pv512 ::= '[' ( _def349 ( ',' _def349 )* )? ']' ;
_pv52 ::= ( _type53 | JSON_NULL ) ;
_pv559 ::= ( _OS_KEY ( JSON_BOOL | ( ( '"hexadecimal"' | '"open_telemetry"' | '"decimal"' | '"datadog"' | '"uuid"' ) | JSON_BOOL ) | _pv48 ) ( _OC_KEY ( JSON_BOOL | ( ( '"hexadecimal"' | '"open_telemetry"' | '"decimal"' | '"datadog"' | '"uuid"' ) | JSON_BOOL ) | _pv48 ) )* '}' ) | '{}' ;
_pv564 ::= ( _OS_KEY ( JSON_BOOL | ( ( '"hexadecimal"' | '"open_telemetry"' | '"decimal"' | '"datadog"' | '"uuid"' ) | JSON_BOOL ) ) ( _OC_KEY ( JSON_BOOL | ( ( '"hexadecimal"' | '"open_telemetry"' | '"decimal"' | '"datadog"' | '"uuid"' ) | JSON_BOOL ) ) )* '}' ) | '{}' ;
_pv569 ::= ( _pv48 | JSON_NULL ) ;
_pv686 ::= ( _OS_KEY _pv399 ( _OC_KEY _pv399 )* '}' ) | '{}' ;
_pv691 ::= '[' ( ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | _def598 ) ( ',' ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | _def598 ) )* )? ']' ;
_pv702 ::= '[' ( _def576 ( ',' _def576 )* )? ']' ;
_pv72 ::= ( _pv48 | JSON_NULL ) ;
_pv746 ::= '[' ( ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | _def604 ) ( ',' ( ( JSON_BOOL | JSON_INTEGER | JSON_NUMBER | JSON_STRING | _def330 ) | _def604 ) )* )? ']' ;
_pv757 ::= '[' ( _def603 ( ',' _def603 )* )? ']' ;
_type53 ::= '[' ( _def54 ( ',' _def54 )* )? ']' ;