use glrmask::{Constraint, Vocab};

fn token_allowed(mask: &[u32], id: usize) -> bool {
    let word = id / 32;
    if word >= mask.len() {
        return false;
    }
    (mask[word] >> (id % 32)) & 1 != 0
}

#[test]
fn test_github_easy_o17408_false_positive_3() {
    let vocab = Vocab::new(
        vec![
            (17u32, b"2".to_vec()),
            (18u32, b"3".to_vec()),
            (471u32, b" U".to_vec()),
        ],
        None,
    );
    let lark = r#"
PATTERN_1: /[\xC2-\xDF]/
PATTERN_2: /[\x80-\xBF]/
PATTERN_3: /[\xE0-\xEF]/
PATTERN_4: /[\xF0-\xF4]/
PATTERN_12: /[\x20-!#-\x5B\x5D-rt-~]/
PATTERN_13: /[\x20-!#-\x5B\x5D-mo-~]/
PATTERN_14: /[\x20-!#-\x5B\x5D-np-~]/
PATTERN_15: /[\x20-!#-\x5B\x5D-hj-~]/
PATTERN_16: /[\x20-!#-\x5B\x5D-su-~]/
PATTERN_17: /[\x20-!#-\x5B\x5D-ce-~]/
PATTERN_18: /[\x20-!#-\x5B\x5D-df-~]/
PATTERN_19: /[\x20-!#-\x5B\x5D-`b-~]/
PATTERN_20: /[\x20-!#-\x5B\x5D-qs-~]/
STRING_CHAR: /[\x20-!#-\x5B\x5D-\x7F]/
    | PATTERN_1 PATTERN_2
    | PATTERN_3 PATTERN_2 PATTERN_2
    | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2
HEX: /[0-9A-Fa-f]/
ESCAPE_SHORT_CHAR: /["\x2F\x5Cbfnrt]/
ESCAPE_SEQ: "\\" ESCAPE_SHORT_CHAR | "\\" "u" HEX HEX HEX HEX
STRING_CONTENT: (STRING_CHAR | ESCAPE_SEQ)*
JSON_STRING: "\"" STRING_CONTENT "\""
DIGIT: /[0-9]/
NONZERO_DIGIT: /[1-9]/
INT_PART: "0" | NONZERO_DIGIT DIGIT*
FRAC_PART: "." DIGIT+
EXP_MARK: /[Ee]/
EXP_SIGN: /[+\x2D]/
EXP_PART: EXP_MARK EXP_SIGN? DIGIT+
JSON_INTEGER: "-"? INT_PART
JSON_NUMBER: "-"? INT_PART FRAC_PART? EXP_PART?
JSON_BOOL: "true" | "false"
JSON_NULL: "null"
JSON_KEY_COLON: JSON_STRING ": "
json_kv: JSON_KEY_COLON json_value
json_object: "{" "}" | "{" json_kv (", " json_kv)* "}"
json_array: "[" "]" | "[" json_value (", " json_value)* "]"
json_value: json_object
    | json_array
    | JSON_STRING
    | JSON_NUMBER
    | JSON_INTEGER
    | JSON_BOOL
    | JSON_NULL
OBJ_ORD_0_CK_0: (/[\x20-!#-\x5B\x5D-~]/ | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
OBJ_ORD_0_CK_1: (PATTERN_12 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "s" OBJ_ORD_0_CK_0
    | ""
OBJ_ORD_0_CK_2: (PATTERN_13 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "n" OBJ_ORD_0_CK_1
    | ""
OBJ_ORD_0_CK_3: (PATTERN_14 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "o" OBJ_ORD_0_CK_2
    | ""
OBJ_ORD_0_CK_4: (PATTERN_15 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "i" OBJ_ORD_0_CK_3
    | ""
OBJ_ORD_0_CK_5: (PATTERN_16 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "t" OBJ_ORD_0_CK_4
    | ""
OBJ_ORD_0_CK_6: (PATTERN_15 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "i" OBJ_ORD_0_CK_5
    | ""
OBJ_ORD_0_CK_7: (PATTERN_17 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "d" OBJ_ORD_0_CK_6
    | ""
OBJ_ORD_0_CK_8: (PATTERN_13 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "n" OBJ_ORD_0_CK_7
    | ""
OBJ_ORD_0_CK_9: (PATTERN_14 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "o" OBJ_ORD_0_CK_8
    | ""
OBJ_ORD_0_CK_11: (PATTERN_18 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "e" OBJ_ORD_0_CK_0
    | ""
OBJ_ORD_0_CK_12: (PATTERN_16 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "t" OBJ_ORD_0_CK_11
    | ""
OBJ_ORD_0_CK_13: (PATTERN_19 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "a" OBJ_ORD_0_CK_12
    | ""
OBJ_ORD_0_CK_15: (PATTERN_13 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "n" OBJ_ORD_0_CK_0
    | ""
OBJ_ORD_0_CK_16: (PATTERN_14 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "o" OBJ_ORD_0_CK_15
    | ""
OBJ_ORD_0_CK_17: (PATTERN_15 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "i" OBJ_ORD_0_CK_16
    | ""
OBJ_ORD_0_CK_18: (PATTERN_16 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "t" OBJ_ORD_0_CK_17
    | ""
OBJ_ORD_0_CK_19: (PATTERN_19 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "a" OBJ_ORD_0_CK_18
    | ""
OBJ_ORD_0_CK_20: (PATTERN_20 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "r" OBJ_ORD_0_CK_19
    | ""
OBJ_ORD_0_CK_21: (PATTERN_15 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "i" OBJ_ORD_0_CK_20
    | ""
OBJ_ORD_0_CK_22: (/[\x20-!#-\x5B\x5D-oq-~]/ | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "p" OBJ_ORD_0_CK_21
    | ""
OBJ_ORD_0_CK_23: (/[\x20-!#-\x5B\x5D-wy-~]/ | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "x" OBJ_ORD_0_CK_22
    | ""
OBJ_ORD_0_CK_25: (PATTERN_17 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "d" OBJ_ORD_0_CK_0
    | ""
OBJ_ORD_0_CK_26: (/[\x20-!#-BF-HJ-\x5B\x5D-~]/ | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "C" OBJ_ORD_0_CK_9
    | "D" OBJ_ORD_0_CK_13
    | "E" OBJ_ORD_0_CK_23
    | "I" OBJ_ORD_0_CK_25
    | ""
OBJ_ORD_0_CK_27: (PATTERN_13 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "n" OBJ_ORD_0_CK_26
    | ""
OBJ_ORD_0_CK_28: (PATTERN_14 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "o" OBJ_ORD_0_CK_27
    | ""
OBJ_ORD_0_CK_29: (PATTERN_15 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "i" OBJ_ORD_0_CK_28
    | ""
OBJ_ORD_0_CK_30: (PATTERN_16 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "t" OBJ_ORD_0_CK_29
    | ""
OBJ_ORD_0_CK_31: (PATTERN_19 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "a" OBJ_ORD_0_CK_30
    | ""
OBJ_ORD_0_CK_32: (/[\x20-!#-\x5B\x5D-bd-~]/ | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "c" OBJ_ORD_0_CK_31
    | ""
OBJ_ORD_0_CK_33: (PATTERN_15 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "i" OBJ_ORD_0_CK_32
    | ""
OBJ_ORD_0_CK_34: (/[\x20-!#-\x5B\x5D-eg-~]/ | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "f" OBJ_ORD_0_CK_33
    | ""
OBJ_ORD_0_CK_35: (PATTERN_15 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "i" OBJ_ORD_0_CK_34
    | ""
OBJ_ORD_0_CK_36: (PATTERN_16 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "t" OBJ_ORD_0_CK_35
    | ""
OBJ_ORD_0_CK_37: (PATTERN_20 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "r" OBJ_ORD_0_CK_36
    | ""
OBJ_ORD_0_CK_38: (PATTERN_18 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "e" OBJ_ORD_0_CK_37
    | ""
OBJ_ORD_0_CK_41: (PATTERN_20 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "r" OBJ_ORD_0_CK_15
    | ""
OBJ_ORD_0_CK_44: (PATTERN_12 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "s" OBJ_ORD_0_CK_11
    | ""
OBJ_ORD_0_CK_45: (PATTERN_19 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "a" OBJ_ORD_0_CK_44
    | ""
OBJ_ORD_0_CK_46: (/[\x20-!#-\x5B\x5D-gi-~]/ | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "h" OBJ_ORD_0_CK_45
    | ""
OBJ_ORD_0_CK_47: (/[\x20-!#-OQ-\x5B\x5D-~]/ | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "P" OBJ_ORD_0_CK_46
    | ""
OBJ_ORD_0_CK_48: (PATTERN_12 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "s" OBJ_ORD_0_CK_47
    | ""
OBJ_ORD_0_CK_49: (PATTERN_19 | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "a" OBJ_ORD_0_CK_48
    | ""
OBJ_ORD_0_CK_50: (/[\x20-!#-\x5B\x5D-bd-eg-rt-~]/ | PATTERN_1 PATTERN_2 | PATTERN_3 PATTERN_2 PATTERN_2 | PATTERN_4 PATTERN_2 PATTERN_2 PATTERN_2) STRING_CONTENT
    | ESCAPE_SEQ STRING_CONTENT
    | "c" OBJ_ORD_0_CK_38
    | "f" OBJ_ORD_0_CK_41
    | "s" OBJ_ORD_0_CK_49
    | ""
OBJ_ORD_0_CK_FULL: "\"" OBJ_ORD_0_CK_50 "\""
STR_TERM_0: OBJ_ORD_0_CK_FULL ": "
obj_ord_0_6_c: ", " STR_TERM_0 json_value obj_ord_0_6_c | ""
obj_ord_0_0_nc: "\"certificationConditions\": " JSON_STRING ", " "\"certificationDate\": " JSON_STRING ", " "\"certificationExpiration\": " JSON_STRING ", " "\"certificationId\": " JSON_STRING ", " "\"frn\": " JSON_STRING ", " "\"sasPhase\": " ("\"1\"" | "\"2\"") obj_ord_0_6_c
start: "{" obj_ord_0_0_nc "}"
"#;

    let c = Constraint::from_lark(lark, &vocab).unwrap();
    let mut s = c.start();
    s.commit_bytes(b"{\"certificationConditions\": \"This device is certified for use in the United States.\", \"certificationDate\": \"2022-01-01\", \"certificationExpiration\": \"2027-01-01\", \"certificationId\": \"DA-123456\", \"frn\": \"0012345678\", \"sasPhase\": \"")
        .unwrap();

    let mask = s.mask();
    assert!(token_allowed(&mask, 17), "token '2' must be allowed at the sasPhase prefix");
    assert!(
        !token_allowed(&mask, 18),
        "token '3' (id=18) must be rejected at the sasPhase prefix"
    );
}