from __future__ import annotations

from typing import Any, Type

import numpy as np

class GrammarExpr:
    @staticmethod
    def ref(name: str) -> GrammarExpr: ...
    @staticmethod
    def sequence(exprs: list[GrammarExpr]) -> GrammarExpr: ...
    @staticmethod
    def choice(exprs: list[GrammarExpr]) -> GrammarExpr: ...
    @staticmethod
    def optional(expr: GrammarExpr) -> GrammarExpr: ...
    @staticmethod
    def repeat(expr: GrammarExpr) -> GrammarExpr: ...
    @staticmethod
    def literal(bytes: bytes) -> GrammarExpr: ...

class RegexExpr:
    @staticmethod
    def eat_u8(c: int) -> RegexExpr: ...
    @staticmethod
    def eat_u8_seq(s: bytes) -> RegexExpr: ...
    @staticmethod
    def eat_u8_set(set: list[int]) -> RegexExpr: ...
    @staticmethod
    def eat_u8_negation(c: int) -> RegexExpr: ...
    @staticmethod
    def eat_u8_set_negation(set: list[int]) -> RegexExpr: ...
    @staticmethod
    def eat_any() -> RegexExpr: ...
    @staticmethod
    def rep(expr: RegexExpr) -> RegexExpr: ...
    @staticmethod
    def rep1(expr: RegexExpr) -> RegexExpr: ...
    @staticmethod
    def opt(expr: RegexExpr) -> RegexExpr: ...
    @staticmethod
    def prec(precedence: int, expr: RegexExpr) -> RegexGroup: ...
    @staticmethod
    def eps() -> RegexExpr: ...
    @staticmethod
    def seq(exprs: list[RegexExpr]) -> RegexExpr: ...
    @staticmethod
    def choice(exprs: list[RegexExpr]) -> RegexExpr: ...
    def build(self) -> Regex: ...

class RegexGroup:
    @staticmethod
    def greedy_group(expr: RegexExpr) -> RegexGroup: ...
    @staticmethod
    def non_greedy_group(expr: RegexExpr) -> RegexGroup: ...

class RegexGroups:
    @staticmethod
    def groups(groups: list[RegexGroup]) -> RegexGroups: ...
    def build(self) -> Regex: ...

class Regex:
    def execute_from_state(self, bytes: bytes, state_id: int) -> tuple[int | None, list[tuple[int, int]]]: ...
    def tokens_accessible_from_state(self, state_id: int) -> list[int]: ...
    def initial_state_id(self) -> int: ...
    def max_state(self) -> int: ...

class GrammarDefinition:
    def __init__(self, rules: list[tuple[str, GrammarExpr]], terminals: list[tuple[str, RegexExpr]]) -> None: ...
    @staticmethod
    def from_ebnf_file(path: str) -> GrammarDefinition: ...
    def simplify(self) -> None: ...
    def compile(self) -> CompiledGrammar: ...
    def print(self) -> None: ...
    def to_json_string(self) -> str: ...
    @staticmethod
    def from_json_string(json_str: str) -> GrammarDefinition: ...

class CompiledGrammar:
    def print(self) -> None: ...
    def to_json_string(self) -> str: ...
    @staticmethod
    def from_json_string(json_str: str) -> CompiledGrammar: ...

class GLRParser:
    def get_parse_table(self) -> dict[str, Any]: ...
    @property
    def ignore_terminal_id(self) -> int | None: ...

class Bitset:
    def __init__(self) -> None: ...
    @staticmethod
    def zeros() -> Bitset: ...
    @staticmethod
    def ones(len: int) -> Bitset: ...
    @staticmethod
    def from_indices(indices: list[int]) -> Bitset: ...
    @staticmethod
    def from_ranges(ranges: list[tuple[int, int]]) -> Bitset: ...
    def to_indices(self) -> list[int]: ...
    def to_ranges(self) -> list[tuple[int, int]]: ...
    def contains(self, idx: int) -> bool: ...
    def insert(self, idx: int) -> None: ...
    def remove(self, idx: int) -> None: ...
    def set(self, idx: int, value: bool) -> None: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...
    def union(self, other: Bitset) -> Bitset: ...
    def intersection(self, other: Bitset) -> Bitset: ...
    def difference(self, other: Bitset) -> Bitset: ...
    def symmetric_difference(self, other: Bitset) -> Bitset: ...
    def is_subset(self, other: Bitset) -> bool: ...
    def to_json_string(self) -> str: ...
    @staticmethod
    def from_json_string(s: str) -> Bitset: ...

class HybridL2Bitset:
    def range_values(self) -> list[tuple[tuple[int, int], Bitset]]: ...
    @staticmethod
    def all() -> HybridL2Bitset: ...
    def union(self, other: HybridL2Bitset) -> HybridL2Bitset: ...
    def complement(self) -> HybridL2Bitset: ...
    def get_l2_bitset(self, state_id: int) -> Bitset: ...
    def insert_l2_bitset(self, state_id: int, bitset: Bitset) -> None: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class GSSNode:
    def __init__(self) -> None: ...
    def ptr(self) -> int: ...
    def is_alive(self) -> bool: ...
    def is_ok(self) -> bool: ...
    def allowed_llm_tokens(self) -> Bitset: ...
    def disallowed_terminals(self) -> HybridL2Bitset: ...
    def clone_node(self) -> GSSNode: ...
    def popn_fast(self, n: int) -> list[tuple[int, GSSNode]]: ...
    def print_stats(self) -> None: ...
    def flatten(self) -> list[tuple[list[int], HybridL2Bitset]]: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def is_root(self) -> bool: ...
    def depth(self) -> int: ...
    def local_acc_terminals_union(self) -> HybridL2Bitset: ...
    def local_acc_llm_tokens_union(self) -> Bitset: ...
    def predecessors(self) -> list[tuple[int, GSSNode]]: ...

class GrammarConstraint:
    def __init__(self, grammar: CompiledGrammar, token_to_id: dict[bytes, int], max_llm_token_id: int) -> None: ...
    def print(self) -> None: ...
    def print_parser(self) -> None: ...
    def to_json_string(self) -> str: ...
    @staticmethod
    def from_json_string(json_str: str) -> GrammarConstraint: ...
    def precompute2_json_string(self) -> str: ...
    def precompute3_json_string(self) -> str: ...
    def get_id_to_token_map(self) -> dict[int, bytes]: ...
    def original_to_internal_map(self) -> dict[int, int]: ...
    def internal_to_original_map(self) -> dict[int, int]: ...
    def internal_bv_to_original(self, bv: Bitset) -> Bitset: ...
    def original_bv_to_internal(self, bv: Bitset) -> Bitset: ...
    def all_internal_llm_tokens_bitset(self) -> Bitset: ...
    def tokenizer(self) -> Regex: ...
    def glr_parser(self) -> GLRParser: ...
    def possible_matches(self) -> dict[int, dict[int, Bitset]]: ...

class GrammarConstraintState:
    def __init__(self, constraint: GrammarConstraint) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def get_mask(self) -> np.ndarray[Any, np.dtype[np.bool_]]: ...
    def get_mask_bv(self) -> Bitset: ...
    def commit(self, llm_token_id: int) -> None: ...
    def print_stats(self) -> None: ...
    def compute_commit_maps(self, llm_token_bytes: bytes) -> tuple[dict[int, int], dict[int, Bitset]]: ...
    def get_state_map(self) -> dict[int, GSSNode]: ...
    def set_state_map(self, new_state: dict[int, GSSNode]) -> None: ...
    def internal_bv_to_original(self, bv: Bitset) -> Bitset: ...

class IncrementalParser:
    def __init__(self, grammar: CompiledGrammar) -> None: ...
    def feed(self, bytes: bytes) -> None: ...
    def is_valid(self) -> bool: ...

def gss_merge_many_with_depth(nodes: list[GSSNode], depth: int) -> GSSNode: ...
def gss_allow_only_llm_tokens_and_prune(node: GSSNode, bv: Bitset) -> None: ...
def gss_reset_llm_tokens(node: GSSNode) -> None: ...
def gss_prune_disallowed_terminals(node: GSSNode, terminals_map: dict[int, Bitset]) -> None: ...
def gss_map_allowed_terminals_tokenizer_states(node: GSSNode, state_map: dict[int, int]) -> None: ...
def gss_fuse_predecessors(node: GSSNode, levels: int) -> None: ...
def gss_popn_collect(node: GSSNode, n: int) -> list[tuple[int, GSSNode]]: ...