from __future__ import annotations

from typing import Any, Type

import numpy as np

class Bitset:
    def __init__(self) -> None: ...
    @staticmethod
    def zeros() -> Bitset: ...
    @staticmethod
    def ones(len: int) -> Bitset: ...
    @staticmethod
    def from_indices(indices: list[int]) -> Bitset: ...
    @staticmethod
    def from_ranges(ranges: list[tuple[int, int]]) -> Bitset: ...
    def to_indices(self) -> list[int]: ...
    def to_ranges(self) -> list[tuple[int, int]]: ...
    def contains(self, idx: int) -> bool: ...
    def insert(self, idx: int) -> None: ...
    def remove(self, idx: int) -> None: ...
    def set(self, idx: int, value: bool) -> None: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...
    def union(self, other: Bitset) -> Bitset: ...
    def intersection(self, other: Bitset) -> Bitset: ...
    def difference(self, other: Bitset) -> Bitset: ...
    def symmetric_difference(self, other: Bitset) -> Bitset: ...
    def is_subset(self, other: Bitset) -> bool: ...
    def to_json_string(self) -> str: ...
    @staticmethod
    def from_json_string(s: str) -> Bitset: ...

class HybridL2Bitset:
    def range_values(self) -> list[tuple[tuple[int, int], Bitset]]: ...
    @staticmethod
    def all() -> HybridL2Bitset: ...
    def union(self, other: HybridL2Bitset) -> HybridL2Bitset: ...
    def complement(self) -> HybridL2Bitset: ...
    def get_l2_bitset(self, state_id: int) -> Bitset: ...
    def insert_l2_bitset(self, state_id: int, bitset: Bitset) -> None: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
