//! The ordinary Ready-port program, instantiated directly in the native
//! finite-weight compiler. Source weights are generated by lexical edges and
//! finals plus identity; the existing global codec retains ghost support.
use super::*;
use crate::compiler::stages::parser_dwa::{FiniteTemplateInstance, FiniteTemplateProgram,
    normalize_finite_template_program};
use crate::compiler::boundary_weight_codec::FaithfulWeightQuotient;
use crate::compiler::boundary_bit_minimize::{FiniteAtomDecoder, minimize_native_decoded};

pub(super) fn compile(
    context: &SignedLinkContext, library: &FragmentLibrary, lexical: &DWA, start_component: u32,
) -> Option<SignedShardOutput> {
    let started = Instant::now();
    let depths = context.closure.max_controls_per_gap as usize + 1;
    if depths > 16 || lexical.states().is_empty() || !lexical.is_acyclic()
        || (depths == 1 && !context.links.is_empty()) { return None; }
    let ports = lexical.states().len().checked_mul(depths)?;
    if ports > 200_000 { return None; }
    let template_ids = library.templates.by_terminal_nwa.keys().enumerate()
        .map(|(i, &t)| (t, i)).collect::<BTreeMap<_, _>>();
    let templates = library.templates.by_terminal_nwa.values().collect::<Vec<_>>();
    let mut coefficients = vec![Weight::all()];
    let mut indices = rustc_hash::FxHashMap::default(); indices.insert(coefficients[0].ptr_key(), 0);
    let mut weight_id = |weight: &Weight| -> usize {
        *indices.entry(weight.ptr_key()).or_insert_with(|| {
            let index = coefficients.len(); coefficients.push(weight.clone()); index
        })
    };
    let mut finals = vec![None; ports];
    let mut instances = Vec::new();
    let mut estimated_states = ports;
    for (q, row) in lexical.states().iter().enumerate() {
        if let Some(weight) = &row.final_weight {
            if !weight.is_empty() { finals[q * depths] = Some(weight_id(weight)); }
        }
        for (label, target, weight) in row.transitions.entries() {
            if label < 0 || target as usize >= lexical.states().len() { return None; }
            if weight.is_empty() { continue; }
            let template = *template_ids.get(&(label as u32))?;
            estimated_states = estimated_states.checked_add(templates[template].states().len())?;
            instances.push(FiniteTemplateInstance {
                template, coefficient: weight_id(weight), continuation: target * depths as u32,
                entries: (q * depths) as u32..((q + 1) * depths) as u32,
            });
        }
    }
    drop(weight_id);
    for q in 0..lexical.states().len() {
        for depth in 0..depths - 1 {
            for link in 0..context.links.len() {
                for key in [library.entry_keys[link], library.finish_keys[link]] {
                    let template = *template_ids.get(&key)?;
                    estimated_states = estimated_states.checked_add(templates[template].states().len())?;
                    let source = (q * depths + depth) as u32;
                    instances.push(FiniteTemplateInstance { template, coefficient: 0,
                        continuation: source + 1, entries: source..source + 1 });
                }
            }
        }
    }
    // Mirror the established finite compiler's policy instead of spending
    // codec work on a tiny shard that will deliberately use its exact fallback.
    if !(4096..=200_000).contains(&estimated_states) || coefficients.len() > 2048 { return None; }
    if std::env::var_os("GLRMASK_PROFILE_COMPOSE").is_some() {
        // Count physical template insertion, not only the compact lexical
        // graph. Keep this diagnostic outside unprofiled performance samples.
        let mut counts = vec![0usize; templates.len()];
        for instance in &instances { counts[instance.template] += 1; }
        let mut groups = BTreeMap::<&str, (usize, usize, usize, usize)>::new();
        let mut largest = Vec::new();
        for (&key, &id) in &template_ids {
            let kind = if library.entry_keys.contains(&key) { "entry" }
                else if library.finish_keys.contains(&key) { "finish" } else { "ordinary" };
            let template = templates[id];
            let states = template.states().len();
            let edges = template.states().iter().map(|row|
                row.epsilons.len() + row.transitions.values().map(Vec::len).sum::<usize>()).sum::<usize>();
            let copies = counts[id];
            let group = groups.entry(kind).or_default();
            group.0 += usize::from(copies != 0);
            group.1 += copies;
            group.2 += states * copies;
            group.3 += edges * copies;
            if copies != 0 {
                largest.push((states * copies, key, kind, copies, states, edges));
            }
        }
        largest.sort_unstable_by(|a,b| b.0.cmp(&a.0).then(a.1.cmp(&b.1)));
        largest.truncate(12);
        eprintln!("[glrmask/profile][boundary_template_census] component={start_component} lexical_states={} lexical_edges={} ports={ports} groups_templates_copies_states_edges={groups:?} largest_totalstates_key_kind_copies_states_edges={largest:?}",
            lexical.num_states(), lexical.num_transitions());
        if std::env::var_os("GLRMASK_PROFILE_BOUNDARY_LEAF_TEMPLATES").is_some() {
            let profile_started=Instant::now();
            let mut counts=BTreeMap::<u32,usize>::new();
            for row in lexical.states() {
                for (label,target,weight) in row.transitions.entries() {
                    if weight.is_empty() {continue;}
                    let next=&lexical.states()[target as usize];
                    if next.final_weight.as_ref().is_some_and(|w|!w.is_empty())
                        && next.transitions.entries().all(|(_,_,w)|w.is_empty()) {
                        *counts.entry(label as u32).or_default()+=1;
                    }
                }
            }
            let mut originals=0usize;let mut projected=0usize;let mut records=Vec::new();
            for (&key,&copies) in &counts {
                let original=library.templates.by_terminal_nwa.get(&key)?;
                let reduced=library.templates.by_terminal.get(&key)
                    .and_then(|dfa|admission::project(dfa,context.total_scoped_states));
                let before=original.states().len();
                let after=reduced.as_ref().map_or(before,|dfa|dfa.states.len());
                originals+=before*copies;projected+=after*copies;
                records.push(((before.saturating_sub(after))*copies,key,copies,before,after,reduced.is_some()));
            }
            records.sort_unstable_by(|a,b|b.0.cmp(&a.0).then(a.1.cmp(&b.1)));
            records.truncate(15);
            eprintln!("[glrmask/profile][boundary_leaf_template_census] component={start_component} keys={} copies={} original_copied_states={originals} projected_copied_states={projected} largest_saving_key_copies_before_after_selected={records:?} diagnostic_ms={:.3}",
                counts.len(),counts.values().sum::<usize>(),profile_started.elapsed().as_secs_f64()*1000.0);
        }
    }
    let certificate = context.predecessor_support.get_or_init(|| {
        let tables = std::iter::once(context.parent_table).chain(context.child_tables.iter().copied()).collect::<Vec<_>>();
        super::super::boundary_stack_support::build(&tables, &context.state_offsets, &context.links, context.total_scoped_states)
    }).as_ref().ok()?;
    let native_context = certificate.native_context()?;
    let domain = Weight::union_all(lexical.states().iter().filter_map(|row| row.final_weight.as_ref()));
    let quotient = FaithfulWeightQuotient::new(&domain, &coefficients)?;
    let decoder = FiniteAtomDecoder::new_checked(quotient.atoms().to_vec())?;
    let encoded = coefficients.iter().map(|weight| quotient.encode(weight)).collect::<Option<Vec<_>>>()?;
    let starts = [lexical.start_state() * depths as u32];
    let program = FiniteTemplateProgram { templates: &templates, coefficients: &encoded,
        port_finals: &finals, starts: &starts, instances: &instances };
    let prepare_ms = started.elapsed().as_secs_f64() * 1000.0;
    let trim = std::env::var_os("GLRMASK_DISABLE_BOUNDARY_DIRECT_PROGRAM_TRIM").is_none();
    let (native, profile) = normalize_finite_template_program(
        &program, context.total_scoped_states, quotient.rows(), Some(&native_context), trim)?;
    if let Some(directory)=std::env::var_os("GLRMASK_DUMP_BOUNDARY_NATIVE_PREMIN") {
        let directory=std::path::PathBuf::from(directory);
        std::fs::create_dir_all(&directory).expect("create native diagnostic directory");
        // Diagnostic only; serialize the unchanged finite normalized graph
        // with its exact decoder. Never used in performance measurements.
        let bytes=bincode::serialize(&(context.total_scoped_states,start_component,
            native.rows,native.token_count,&native.states,&native.weights,quotient.atoms()))
            .expect("serialize native pre-min graph and decoder");
        let compressed=zstd::stream::encode_all(bytes.as_slice(),1).expect("compress native diagnostic");
        std::fs::write(directory.join(format!("component-{start_component}-native.bin.zst")),compressed)
            .expect("write native pre-min diagnostic");
    }
    let minimize_started = Instant::now();
    let (parser_dwa, min_profile) = minimize_native_decoded(
        &native, &decoder, crate::compiler::glr::labels::DEFAULT_LABEL)?;
    let minimize_ms = minimize_started.elapsed().as_secs_f64() * 1000.0;
    if std::env::var_os("GLRMASK_PROFILE_COMPOSE").is_some() {
        eprintln!("[glrmask/profile][boundary_direct_program] component={start_component} templates={} instances={} coefficients={} points={} atoms={} prepare_ms={prepare_ms:.3} minimize_ms={minimize_ms:.3} total_ms={:.3} native={profile:?} minimize={min_profile:?}",
            templates.len(), instances.len(), coefficients.len(), quotient.point_count(), quotient.atom_count(),
            started.elapsed().as_secs_f64()*1000.0);
    }
    Some(SignedShardOutput { parser_dwa, templates_ms: library.templates_ms,
        compose_ms: prepare_ms + profile.assembly_ms + profile.early_top_ms + profile.early_trim_ms + profile.support_ms + profile.trim_ms,
        resolve_ms: profile.resolve_ms, normalize_ms: profile.normalize_ms + minimize_ms,
        signed_states: profile.input_states, signed_transitions: profile.input_edges, terms: library.ordinary_terms })
}
