//! The ordinary Ready-port program, instantiated directly in the native
//! finite-weight compiler. Source weights are generated by lexical edges and
//! finals plus identity; the existing global codec retains ghost support.
use super::*;
use crate::compiler::stages::parser_dwa::{FiniteTemplateInstance, FiniteTemplateProgram,
    normalize_finite_template_program};
use crate::compiler::boundary_weight_codec::FaithfulWeightQuotient;
use crate::compiler::boundary_bit_minimize::{FiniteAtomDecoder, minimize_native_decoded};

pub(super) fn compile(
    context: &SignedLinkContext, library: &FragmentLibrary, lexical: &DWA, start_component: u32,
) -> Option<SignedShardOutput> {
    let started = Instant::now();
    let depths = context.closure.max_controls_per_gap as usize + 1;
    if depths > 16 || lexical.states().is_empty() || !lexical.is_acyclic()
        || (depths == 1 && !context.links.is_empty()) { return None; }
    let ports = lexical.states().len().checked_mul(depths)?;
    if ports > 200_000 { return None; }
    let template_ids = library.templates.by_terminal_nwa.keys().enumerate()
        .map(|(i, &t)| (t, i)).collect::<BTreeMap<_, _>>();
    let templates = library.templates.by_terminal_nwa.values().collect::<Vec<_>>();
    let mut coefficients = vec![Weight::all()];
    let mut indices = rustc_hash::FxHashMap::default(); indices.insert(coefficients[0].ptr_key(), 0);
    let mut weight_id = |weight: &Weight| -> usize {
        *indices.entry(weight.ptr_key()).or_insert_with(|| {
            let index = coefficients.len(); coefficients.push(weight.clone()); index
        })
    };
    let mut finals = vec![None; ports];
    let mut instances = Vec::new();
    let mut estimated_states = ports;
    for (q, row) in lexical.states().iter().enumerate() {
        if let Some(weight) = &row.final_weight {
            if !weight.is_empty() { finals[q * depths] = Some(weight_id(weight)); }
        }
        for (label, target, weight) in row.transitions.entries() {
            if label < 0 || target as usize >= lexical.states().len() { return None; }
            if weight.is_empty() { continue; }
            let template = *template_ids.get(&(label as u32))?;
            estimated_states = estimated_states.checked_add(templates[template].states().len())?;
            instances.push(FiniteTemplateInstance {
                template, coefficient: weight_id(weight), continuation: target * depths as u32,
                entries: (q * depths) as u32..((q + 1) * depths) as u32,
            });
        }
    }
    drop(weight_id);
    for q in 0..lexical.states().len() {
        for depth in 0..depths - 1 {
            for link in 0..context.links.len() {
                for key in [library.entry_keys[link], library.finish_keys[link]] {
                    let template = *template_ids.get(&key)?;
                    estimated_states = estimated_states.checked_add(templates[template].states().len())?;
                    let source = (q * depths + depth) as u32;
                    instances.push(FiniteTemplateInstance { template, coefficient: 0,
                        continuation: source + 1, entries: source..source + 1 });
                }
            }
        }
    }
    // Mirror the established finite compiler's policy instead of spending
    // codec work on a tiny shard that will deliberately use its exact fallback.
    if !(4096..=200_000).contains(&estimated_states) || coefficients.len() > 2048 { return None; }
    let certificate = context.predecessor_support.get_or_init(|| {
        let tables = std::iter::once(context.parent_table).chain(context.child_tables.iter().copied()).collect::<Vec<_>>();
        super::super::boundary_stack_support::build(&tables, &context.state_offsets, &context.links, context.total_scoped_states)
    }).as_ref().ok()?;
    let native_context = certificate.native_context()?;
    let domain = Weight::union_all(lexical.states().iter().filter_map(|row| row.final_weight.as_ref()));
    let quotient = FaithfulWeightQuotient::new(&domain, &coefficients)?;
    let decoder = FiniteAtomDecoder::new_checked(quotient.atoms().to_vec())?;
    let encoded = coefficients.iter().map(|weight| quotient.encode(weight)).collect::<Option<Vec<_>>>()?;
    let starts = [lexical.start_state() * depths as u32];
    let program = FiniteTemplateProgram { templates: &templates, coefficients: &encoded,
        port_finals: &finals, starts: &starts, instances: &instances };
    let prepare_ms = started.elapsed().as_secs_f64() * 1000.0;
    let trim = std::env::var_os("GLRMASK_DISABLE_BOUNDARY_DIRECT_PROGRAM_TRIM").is_none();
    let (native, profile) = normalize_finite_template_program(
        &program, context.total_scoped_states, quotient.rows(), Some(&native_context), trim)?;
    let minimize_started = Instant::now();
    let (parser_dwa, min_profile) = minimize_native_decoded(
        &native, &decoder, crate::compiler::glr::labels::DEFAULT_LABEL)?;
    let minimize_ms = minimize_started.elapsed().as_secs_f64() * 1000.0;
    if std::env::var_os("GLRMASK_PROFILE_COMPOSE").is_some() {
        eprintln!("[glrmask/profile][boundary_direct_program] component={start_component} templates={} instances={} coefficients={} points={} atoms={} prepare_ms={prepare_ms:.3} minimize_ms={minimize_ms:.3} total_ms={:.3} native={profile:?} minimize={min_profile:?}",
            templates.len(), instances.len(), coefficients.len(), quotient.point_count(), quotient.atom_count(),
            started.elapsed().as_secs_f64()*1000.0);
    }
    Some(SignedShardOutput { parser_dwa, templates_ms: library.templates_ms,
        compose_ms: prepare_ms + profile.assembly_ms + profile.support_ms + profile.trim_ms,
        resolve_ms: profile.resolve_ms, normalize_ms: profile.normalize_ms + minimize_ms,
        signed_states: profile.input_states, signed_transitions: profile.input_edges, terms: library.ordinary_terms })
}
