//! Publication-facing API facade.
//!
//! This module is the intentionally small surface that downstream users should
//! read first.  The rest of the crate is organized around implementation
//! subsystems: frontends, grammar normalization, automata construction, parser
//! analysis, and runtime masking/commit.  Those subsystems are important, but
//! they are not the conceptual API.
//!
//! # Mathematical boundary
//!
//! A compiled [`Constraint`] denotes the decoding constraint for one grammar and
//! one vocabulary.  A [`ConstraintState`] denotes one point in a generated byte
//! stream: it stores the current lexer states and parser stacks.  Runtime use is
//! just the alternating pair of operations from the paper:
//!
//! 1. **Mask**: compute the set of vocabulary tokens that can be emitted next.
//! 2. **Commit**: consume the bytes of the selected token and advance the state.
//!
//! Everything below this facade exists to make those two operations fast.
//!
//! # Public modules
//!
//! - [`constraint`] exposes the immutable compiled artifact.
//! - [`state`] exposes the mutable per-generation state.
//! - [`vocab`] exposes the vocabulary representation.
//! - [`error`] exposes crate errors and `Result`.
//! - [`profiles`] exposes measurement types that are intentionally supported.
//! - [`options`] reserves the stable place for publication-facing configuration.
//! - [`introspection`] exposes parser/grammar inspection types returned by the
//!   public API.

pub mod constraint;
pub mod error;
pub mod introspection;
pub mod options;
pub mod profiles;
pub mod state;
pub mod vocab;

#[doc(inline)]
pub use constraint::Constraint;
#[doc(inline)]
pub use error::{Error, GlrMaskError, Result};
#[doc(inline)]
pub use introspection::{TableAmbiguity, TableAmbiguityKind};
#[doc(inline)]
pub use options::{CompileOptions, RuntimeOptions};
#[doc(inline)]
pub use profiles::{
    AdvanceProfile,
    AdvanceTrace,
    AdvanceTraceGoto,
    AdvanceTraceReduce,
    AdvanceTraceStep,
    AdvanceTraceWave,
    CommitProfile,
    GssProfileSummary,
    MaskProfile,
    PerAdvanceEntry,
};
#[doc(inline)]
pub use state::{ConstraintState, State};
#[doc(inline)]
pub use vocab::Vocab;
