#!/usr/bin/env python3
"""
Generate a random valid unified diff for a given source file.

This generates diffs that should be accepted by the grammar generated by generate_diff_grammar.py.
The diffs include various challenging cases to test the grammar constraint:
- Single line additions
- Single line deletions
- Multi-line changes
- Unchanged context lines
- Edge cases (empty lines, special characters)
"""

import argparse
import random
import sys
from pathlib import Path


def generate_random_diff(source_file: str, seed: int = None) -> str:
    """Generate a random valid unified diff for the given source file."""
    if seed is not None:
        random.seed(seed)
    
    # Read source file
    with open(source_file, 'r') as f:
        original_lines = f.readlines()
    
    # Strip trailing newlines for easier manipulation
    original_lines = [line.rstrip('\n') for line in original_lines]
    
    if not original_lines:
        print("Warning: Source file is empty", file=sys.stderr)
        return ""
    
    # Generate file header
    diff_parts = [
        f"diff --git a/{Path(source_file).name} b/{Path(source_file).name}",
        "index abc1234..def5678 100644",
        f"--- a/{Path(source_file).name}",
        f"+++ b/{Path(source_file).name}",
    ]
    
    # Decide what kind of changes to make
    num_hunks = random.randint(1, min(5, max(1, len(original_lines) // 50)))
    
    # Generate hunks
    used_line_ranges = []
    
    for _ in range(num_hunks):
        # Pick a random starting line (0-indexed)
        # Avoid overlapping with previous hunks
        max_attempts = 100
        for attempt in range(max_attempts):
            start_line = random.randint(0, len(original_lines) - 1)
            context_before = min(3, start_line)
            context_after = min(3, len(original_lines) - start_line - 1)
            
            # Check for overlap
            hunk_start = start_line - context_before
            hunk_end = start_line + context_after + 10  # Rough estimate
            
            overlap = False
            for (used_start, used_end) in used_line_ranges:
                if not (hunk_end < used_start or hunk_start > used_end):
                    overlap = True
                    break
            
            if not overlap:
                break
        else:
            # Couldn't find non-overlapping position, skip this hunk
            continue
        
        # Decide change type
        change_types = ['add', 'delete', 'modify', 'multi_add', 'multi_delete', 'multi_modify']
        change_type = random.choice(change_types)
        
        # Build the hunk
        hunk_lines = []
        old_start = start_line - context_before + 1  # 1-indexed
        new_start = old_start  # Will be same for now
        old_count = 0
        new_count = 0
        
        # Add context before
        for i in range(context_before):
            line_idx = start_line - context_before + i
            if 0 <= line_idx < len(original_lines):
                hunk_lines.append((' ', original_lines[line_idx]))
                old_count += 1
                new_count += 1
        
        # Add the change
        if change_type == 'add':
            # Add one new line
            hunk_lines.append(('+', generate_random_code_line()))
            new_count += 1
            
        elif change_type == 'delete':
            # Delete the current line
            if start_line < len(original_lines):
                hunk_lines.append(('-', original_lines[start_line]))
                old_count += 1
                
        elif change_type == 'modify':
            # Replace one line
            if start_line < len(original_lines):
                hunk_lines.append(('-', original_lines[start_line]))
                old_count += 1
                hunk_lines.append(('+', generate_modified_line(original_lines[start_line])))
                new_count += 1
                
        elif change_type == 'multi_add':
            # Add multiple lines
            num_add = random.randint(2, 5)
            for _ in range(num_add):
                hunk_lines.append(('+', generate_random_code_line()))
                new_count += 1
                
        elif change_type == 'multi_delete':
            # Delete multiple lines
            num_del = random.randint(2, min(5, len(original_lines) - start_line))
            for i in range(num_del):
                line_idx = start_line + i
                if line_idx < len(original_lines):
                    hunk_lines.append(('-', original_lines[line_idx]))
                    old_count += 1
                    
        elif change_type == 'multi_modify':
            # Replace multiple lines
            num_mod = random.randint(2, min(5, len(original_lines) - start_line))
            for i in range(num_mod):
                line_idx = start_line + i
                if line_idx < len(original_lines):
                    hunk_lines.append(('-', original_lines[line_idx]))
                    old_count += 1
            for _ in range(random.randint(1, num_mod + 2)):
                hunk_lines.append(('+', generate_random_code_line()))
                new_count += 1
        
        # Add context after
        for i in range(context_after):
            line_idx = start_line + 1 + i
            if change_type in ['delete', 'multi_delete', 'modify', 'multi_modify']:
                # Adjust for deleted lines
                if change_type in ['delete', 'modify']:
                    line_idx = start_line + 1 + i
                elif change_type == 'multi_delete':
                    line_idx = start_line + old_count - context_before + i
                elif change_type == 'multi_modify':
                    line_idx = start_line + old_count - context_before + i
            if 0 <= line_idx < len(original_lines):
                hunk_lines.append((' ', original_lines[line_idx]))
                old_count += 1
                new_count += 1
        
        # Build hunk header
        hunk_header = f"@@ -{old_start},{old_count} +{new_start},{new_count} @@"
        diff_parts.append(hunk_header)
        
        # Add hunk lines
        for prefix, content in hunk_lines:
            diff_parts.append(f"{prefix}{content}")
        
        # Track used range
        used_line_ranges.append((hunk_start, start_line + old_count))
    
    # Add EOF marker
    diff_parts.append("<|EOF|>")
    
    return '\n'.join(diff_parts)


def generate_random_code_line() -> str:
    """Generate a random line of code."""
    patterns = [
        "    // TODO: implement this",
        "    let x = 42;",
        "    println!(\"debug\");",
        "    assert!(result.is_ok());",
        "    return Some(value);",
        "",  # Empty line
        "    // Comment with special chars: <>\"'&",
        "    let mut buffer = Vec::new();",
        "    fn helper() {}",
        "    use super::*;",
        "        // Nested indent",
        "    if condition { return; }",
    ]
    return random.choice(patterns)


def generate_modified_line(original: str) -> str:
    """Generate a modified version of an existing line."""
    # Simple modifications
    if not original.strip():
        return "    // Added comment"
    
    if original.strip().startswith("//"):
        return original.replace("//", "/* ") + " */"
    
    if "let" in original:
        return original.replace("let", "let mut")
    
    if "fn " in original:
        return original.replace("fn ", "pub fn ")
    
    # Default: add a comment at the end
    return original + " // modified"


def main():
    parser = argparse.ArgumentParser(
        description="Generate a random valid unified diff for testing grammar constraints"
    )
    parser.add_argument("source_file", help="Path to the source file to generate diff for")
    parser.add_argument("-o", "--output", help="Output file (default: stdout)")
    parser.add_argument("--seed", type=int, help="Random seed for reproducibility")
    
    args = parser.parse_args()
    
    diff = generate_random_diff(args.source_file, args.seed)
    
    if args.output:
        with open(args.output, 'w') as f:
            f.write(diff)
        print(f"Generated diff written to {args.output}", file=sys.stderr)
    else:
        print(diff)


if __name__ == "__main__":
    main()
