//! Live runtime state for one generated prefix.
//!
//! This module owns the mutable half of the runtime denotation.  The immutable
//! [`Constraint`](crate::runtime::constraint::Constraint) is the compiled
//! object; a [`ConstraintState`] is the current frontier of lexer states and
//! parser stacks after a generated byte prefix.  Mask reads this frontier.
//! Commit replaces it with the successor frontier.

mod cache;
mod force;
mod inspect;
mod scratch;

use std::collections::BTreeMap;
use std::sync::Mutex;

use crate::parser::glr::advance::ParserGSS;

use super::constraint::Constraint;

pub(crate) use cache::{MaskCacheData, MaskScratch};
pub(crate) use scratch::CommitBuffers;

/// Mutable runtime state for one generated byte sequence.
///
/// A `ConstraintState` is the runtime object on which Mask and Commit alternate.
/// It borrows the immutable [`Constraint`] and owns the active frontier of
/// tokenizer states and GLR parser stacks for the bytes committed so far.
///
/// Cloning a state clones the logical frontier but starts with empty scratch and
/// mask caches; scratch buffers are performance details, not semantics.
pub struct ConstraintState<'a> {
    pub(crate) constraint: &'a Constraint,
    pub(crate) state: BTreeMap<u32, ParserGSS>,
    pub(crate) buffers: CommitBuffers,
    /// Monotonically increasing counter, bumped on every commit.
    /// Used for cheap cache invalidation in fill_mask.
    pub(crate) generation: u64,
    /// Cached fill_mask result: returned directly when state matches cached snapshot.
    /// Not cloned — clone starts with empty cache.
    pub(crate) mask_cache: Mutex<Option<MaskCacheData>>,
    /// Reusable scratch buffers for fill_mask to avoid per-call allocation.
    pub(crate) mask_scratch: Mutex<MaskScratch>,
}

impl<'a> Clone for ConstraintState<'a> {
    fn clone(&self) -> Self {
        ConstraintState {
            constraint: self.constraint,
            state: self.state.clone(),
            buffers: self.buffers.clone(),
            generation: self.generation,
            mask_cache: Mutex::new(None),
            mask_scratch: Mutex::new(MaskScratch::default()),
        }
    }
}

impl<'a> std::fmt::Debug for ConstraintState<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ConstraintState")
            .field("state_len", &self.state.len())
            .field("mask_cached", &self.mask_cache.lock().unwrap().is_some())
            .finish()
    }
}
