use crate::finite_automata::Regex;
use hashbrown::HashMap;
use rayon::prelude::*;
use std::collections::BTreeMap;
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};

pub struct SimpleEquivalenceResult {
    pub mask_classes: BTreeMap<Vec<usize>, Vec<usize>>,
}

/// Helper: Simulates the DFA walk on a slice.
/// Returns a list of (group_id, width) for matches, and the lookahead IDs if it survives.
fn get_branches_and_lookahead(
    regex: &Regex,
    slice: &[u8],
    start_node: usize
) -> (Vec<(usize, usize)>, Option<&[usize]>) {
    let mut curr = start_node;
    let mut branches = Vec::new();

    for (i, &b) in slice.iter().enumerate() {
        match regex.dfa.states[curr].transitions.get(b) {
            Some(&next) => {
                curr = next;
                // Found a match: this creates a branch in the tree
                for gid in regex.dfa.states[curr].finalizers.iter_indices() {
                    branches.push((gid, i + 1)); // i + 1 is the width
                }
            }
            None => return (branches, None), // Dead end
        }
    }
    // Survived to end: return lookaheads as the "leaves"
    (branches, Some(&regex.dfa.states[curr].possible_future_group_ids))
}

/// Recursively hashes the tree of events generated by a token.
/// Tree Nodes = DFA executions.
/// Tree Edges = Matches found (triggering a restart).
/// Tree Leaves = Lookahead IDs (allowed future tokens).
fn compute_tree_hash(regex: &Regex, slice: &[u8], start_node: usize) -> u64 {
    let mut hasher = DefaultHasher::new();

    // 1. Run execution for this node
    let (matches, lookahead) = get_branches_and_lookahead(regex, slice, start_node);

    // 2. Hash the branches (Recursive Step)
    // Each match triggers a new logical thread starting from the DFA root
    for (group_id, width) in matches {
        group_id.hash(&mut hasher);
        // Recurse on the remaining suffix
        let suffix_hash = compute_tree_hash(regex, &slice[width..], regex.dfa.start_state);
        suffix_hash.hash(&mut hasher);
    }

    // 3. Hash the leaves (Lookahead)
    if let Some(ids) = lookahead {
        // We surived: Hash the valid next tokens
        for id in ids {
            id.hash(&mut hasher);
        }
    } else {
        // We died: Hash a dead-end marker
        0xFF_u8.hash(&mut hasher);
    }

    hasher.finish()
}

pub fn find_equivalence_classes(
    regex: &Regex,
    strings: &[Vec<u8>],
    initial_states: &[usize],
) -> SimpleEquivalenceResult {
    // Compute signature for every string
    let signatures: Vec<u64> = strings.par_iter().map(|s| {
        let mut hasher = DefaultHasher::new();
        // The token must produce the exact same tree structure for every possible start state
        for &start_node in initial_states {
            start_node.hash(&mut hasher);
            let tree_hash = compute_tree_hash(regex, s, start_node);
            tree_hash.hash(&mut hasher);
        }
        hasher.finish()
    }).collect();

    // Group by signature
    let mut groups = HashMap::new();
    for (idx, sig) in signatures.into_iter().enumerate() {
        groups.entry(sig).or_insert_with(Vec::new).push(idx);
    }

    SimpleEquivalenceResult {
        mask_classes: groups.into_iter()
            .enumerate()
            .map(|(id, (_, idxs))| (vec![id], idxs))
            .collect(),
    }
}