--- a/src/js.ebnf
+++ b/src/js.ebnf
@@ -106,37 +106,71 @@
 assignment_expression ::=
     yield_expression
   | arrow_function
-  | conditional_expression
-  | left_hand_side_expression ( '=' | '+=' | '-=' | '*=' | '/=' | '%=' | '<<=' | '>>=' | '>>>=' | '&=' | '^=' | '|=' | '**=' ) assignment_expression
+  | assignment_expression assignment_operator conditional_expression
+  | conditional_expression
   ;
+assignment_operator ::= '=' | '+=' | '-=' | '*=' | '/=' | '%=' | '<<=' | '>>=' | '>>>=' | '&=' | '^=' | '|=' | '**=' ;
 
 arrow_function ::= arrow_parameters '=>' ( block | expression ) ;
 arrow_parameters ::= IDENTIFIER | '(' parameter_list? ')' ;
 
 conditional_expression ::=
-    coalesce_expression ( '?' assignment_expression ':' assignment_expression )?
+    coalesce_expression ( '?' assignment_expression ':' assignment_expression )?
   ;
 
-coalesce_expression ::= logical_or_expression ( '??' logical_or_expression )* ;
-
-logical_or_expression ::= logical_and_expression ( '||' logical_and_expression )* ;
-
-logical_and_expression ::= bitwise_or_expression ( '&&' bitwise_or_expression )* ;
-
-bitwise_or_expression ::= bitwise_xor_expression ( '|' bitwise_xor_expression )* ;
-
-bitwise_xor_expression ::= bitwise_and_expression ( '^' bitwise_and_expression )* ;
-
-bitwise_and_expression ::= equality_expression ( '&' equality_expression )* ;
-
-equality_expression ::= relational_expression ( ( '==' | '!=' | '===' | '!==' ) relational_expression )* ;
-
-relational_expression ::= shift_expression ( ( '<' | '>' | '<=' | '>=' | 'instanceof' | 'in' ) shift_expression )* ;
-
-shift_expression ::= additive_expression ( ( '<<' | '>>' | '>>>' ) additive_expression )* ;
-
-additive_expression ::= multiplicative_expression ( ( '+' | '-' ) multiplicative_expression )* ;
-
-multiplicative_expression ::= exponentiation_expression ( ( '*' | '/' | '%' ) exponentiation_expression )* ;
-
-exponentiation_expression ::= unary_expression ( '**' exponentiation_expression )? ;
+coalesce_expression ::=
+    coalesce_expression '??' logical_or_expression
+  | logical_or_expression
+  ;
+
+logical_or_expression ::=
+    logical_or_expression '||' logical_and_expression
+  | logical_and_expression
+  ;
+
+logical_and_expression ::=
+    logical_and_expression '&&' bitwise_or_expression
+  | bitwise_or_expression
+  ;
+
+bitwise_or_expression ::=
+    bitwise_or_expression '|' bitwise_xor_expression
+  | bitwise_xor_expression
+  ;
+
+bitwise_xor_expression ::=
+    bitwise_xor_expression '^' bitwise_and_expression
+  | bitwise_and_expression
+  ;
+
+bitwise_and_expression ::=
+    bitwise_and_expression '&' equality_expression
+  | equality_expression
+  ;
+
+equality_expression ::=
+    equality_expression equality_operator relational_expression
+  | relational_expression
+  ;
+equality_operator ::= '==' | '!=' | '===' | '!==' ;
+
+relational_expression ::=
+    relational_expression relational_operator shift_expression
+  | shift_expression
+  ;
+relational_operator ::= '<' | '>' | '<=' | '>=' | 'instanceof' | 'in' ;
+
+shift_expression ::=
+    shift_expression shift_operator additive_expression
+  | additive_expression
+  ;
+shift_operator ::= '<<' | '>>' | '>>>' ;
+
+additive_expression ::=
+    additive_expression additive_operator multiplicative_expression
+  | multiplicative_expression
+  ;
+additive_operator ::= '+' | '-' ;
+
+multiplicative_expression ::=
+    multiplicative_expression multiplicative_operator exponentiation_expression
+  | exponentiation_expression
+  ;
+multiplicative_operator ::= '*' | '/' | '%' ;
+
+exponentiation_expression ::=
+    exponentiation_expression '**' unary_expression
+  | unary_expression
+  ;
 
 unary_expression ::=
     ( 'delete' | 'void' | 'typeof' | '++' | '--' | '+' | '-' | '~' | '!' | 'await' )* postfix_expression
