// Instruct the parser to ignore Whitespace and single-line Comments.
#![ignore(IGNORE)]

// --- Lexical Grammar (Minimal) ---
IGNORE ::= WS | MULTI_LINE_COMMENT ;
WS ::= ' ' ;
MULTI_LINE_COMMENT ::= '/*' ( [^*] | '*' [^/] )* '*/' ;

program ::= 'x' '=' EOF
EOF ::= '<|EOF|>' ;
