// Instruct the parser to ignore Whitespace and Comments between tokens.
#![ignore(IGNORE)]

program ::= statement_list? EOF;
EOF ::= '<|EOF|>';

// --- Lexical Grammar ---
IGNORE ::= ( WS | COMMENT )+ ;
WS ::= ( ' ' | '\t' | '\n' | '\r' )+ ;
COMMENT ::= SINGLE_LINE_COMMENT | MULTI_LINE_COMMENT ;
SINGLE_LINE_COMMENT ::= '//' ( [^\n\r] )* ;
MULTI_LINE_COMMENT ::= '/*' ( [^*] | '*' [^/] )* '*/' ;

// --- Statements (Intermediate set) ---
statement_list ::= statement+ ;

statement ::=
    block
  | declaration_statement
  | function_declaration
  | expression_statement
  ;

expression_statement ::= expression ';'? ;
block ::= '{' statement_list? '}' ;

declaration_statement ::= ( 'var' | 'let' | 'const' ) variable_declaration_list ';'? ;
variable_declaration_list ::= variable_declaration ( ',' variable_declaration )* ;
variable_declaration ::= binding_pattern ( '=' expression )? ;

binding_pattern ::= IDENTIFIER ;

function_declaration ::= 'function' IDENTIFIER '(' parameter_list? ')' block ;
parameter_list ::= formal_parameter ( ',' formal_parameter )* ;
formal_parameter ::= binding_pattern ( '=' expression )? ;

// --- Expressions (Intermediate Precedence Hierarchy) ---
expression ::= assignment_expression ;

assignment_expression ::=
    arrow_function
  | conditional_expression
  | left_hand_side_expression ( '=' | '+=' | '-=' | '*=' | '/=' | '%=' | '**=' ) assignment_expression
  ;

arrow_function ::= arrow_parameters '=>' ( block | expression ) ;
arrow_parameters ::= IDENTIFIER | '(' parameter_list? ')' ;

conditional_expression ::=
    logical_or_expression ( '?' expression ':' expression )?
  ;

logical_or_expression ::= logical_and_expression ( '||' logical_