// Instruct the parser to ignore Whitespace and single-line Comments.
#![ignore(IGNORE)]

program ::= 'x' '=' ;

// --- Lexical Grammar (Minimal) ---
IGNORE ::= ( ' ' | MULTI_LINE_COMMENT )+ ;
WS ::= ' ' ;
MULTI_LINE_COMMENT ::= '/*' ;

