program ::= statement? EOF ;
EOF ::= '<|EOF|>' ;

statement ::=
    if_statement
  | block
  | expression_statement
  ;

if_statement ::= 'if' '(' 'true' ')' statement ;

block ::= '{' statement* '}'? ;               // allow prefix to keep parsing

expression_statement ::= object_literal ';'? ;

object_literal ::= '{' method_list? '}'? ;    // allow prefix to keep parsing

method_list ::= method ( ',' method )* ;
method ::= 'if' '(' 'true' ')' block ;        // lets "{ if (true) {" be valid inside an object